server:
  port: 8079

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payments}
    username: ${SPRING_DATASOURCE_USERNAME:payments}
    password: ${SPRING_DATASOURCE_PASSWORD:payments}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: auth
  flyway:
    enabled: true
    create-schemas: true
    schemas: auth
    default-schema: auth

security:
  jwt:
    secret: ${JWT_SECRET:otel-payment-poc-local-secret-key-32bytes-minimum!}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
