server:
  port: 8083

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: payments
    password: payments
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: notification
  flyway:
    enabled: true
    create-schemas: true
    schemas: notification
    default-schema: notification
  rabbitmq:
    host: localhost
    port: 5672
    username: payments
    password: payments
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 2.0
          max-interval: 5000ms

security:
  jwt:
    secret: ${JWT_SECRET:change-this-demo-secret-change-this-demo-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
