server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${SERVICES_AUTH_URL:http://localhost:8079}
              predicates:
                - Path=/api/v1/auth/**
            - id: customer-service
              uri: ${SERVICES_CUSTOMER_URL:http://localhost:8084}
              predicates:
                - Path=/api/v1/customers/**
            - id: payment-service
              uri: ${SERVICES_PAYMENT_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/payments/**
            - id: transfer-service
              uri: ${SERVICES_PAYMENT_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/transfers/**
            - id: notification-service
              uri: ${SERVICES_NOTIFICATION_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/notifications/**

security:
  jwt:
    secret: ${JWT_SECRET:change-this-demo-secret-change-this-demo-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      probes:
        enabled: true

logging:
  structured:
    format:
      console: logstash


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
