#!/usr/bin/env python3
"""Regenerate the self-contained manager/support guide from repository configuration and run evidence."""
from pathlib import Path
from html import escape as e
import base64
import datetime
import json
import os
import subprocess
import xml.etree.ElementTree as ET
from guide_markdown import render_markdown

ROOT = Path(__file__).resolve().parents[1]
os.chdir(ROOT)

def git(*args):
    return subprocess.check_output(['git', *args], text=True).strip()

revision=os.environ.get('POC_EVIDENCE_REVISION') or git('rev-parse','HEAD')
ref=os.environ.get('GITHUB_HEAD_REF') or os.environ.get('GITHUB_REF_NAME') or git('branch','--show-current') or 'main'
source='https://github.com/srinu7893/otel-payment-platform-poc/blob/'+ref+'/'
def read_artifact(name, default=None):
    path=ROOT/'artifacts'/name
    return json.loads(path.read_text()) if path.exists() else default

results=read_artifact('otel-results.json', [])
pipeline=json.loads(os.environ.get('POC_PIPELINE_OUTCOMES','{}'))
browser=read_artifact('browser-results.json', {})
traffic=read_artifact('traffic.json', {})
sampling=read_artifact('advanced-sampling.json', {})
support_results=read_artifact('support-results.json', [])
synthetic=read_artifact('synthetic-journey.json', {})
test_totals={k:0 for k in ('tests','failures','errors','skipped')}
for path in ROOT.glob('**/target/surefire-reports/TEST-*.xml'):
    suite=ET.parse(path).getroot()
    for key in test_totals:
        test_totals[key]+=int(suite.attrib.get(key,0))
verified=bool(support_results) and all(x['status']=='PASS' for x in support_results) and synthetic.get('status')=='PASS' and bool(results) and all(x['status']=='PASS' for x in results) and browser.get('status')=='PASS' and sampling.get('status')=='PASS' and bool(pipeline) and all(x=='success' for x in pipeline.values())
sections=[]
def section(key,title,body):
    sections.append((key,title,body))
def p(text): return '<p>'+e(text)+'</p>'
def code(text): return '<pre><code>'+e(text)+'</code></pre>'
def link(url,label): return '<a href="'+e(url,quote=True)+'">'+e(label)+'</a>'
def file(path,label=None): return link(source+path,label or path)
def table(headers,rows):
    return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+e(x)+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def bullets(items): return '<ul>'+''.join('<li>'+x+'</li>' for x in items)+'</ul>'

section('summary','Manager overview',p('A simulated payment platform demonstrating synchronous HTTP calls, database transactions, durable asynchronous delivery and OpenTelemetry across seven Java services. No real money, bank, SMS or email providers are involved.')+
p('This increment implements the local observability stack and executable acceptance gates. Configuration and source presence do not prove runtime success: use the Evidence section to see what actually ran. Cloud Run runtime/release assets and optional BigQuery queries are now prepared; actual cloud execution and production hardening remain separate evidence gates.')+
table(['Outcome','Implementation / acceptance'],[
 ('Follow a payment end to end','Java agent → HTTP/JDBC spans → persisted outbox trace context → RabbitMQ consumer; asserted by a single connected trace in Tempo.'),
 ('Diagnose delays and failures','HTTP rate/error/duration, JVM metrics, business event logs, outbox attempt counter, service graph and trace/log navigation.'),
 ('Reproduce the demonstration','Pinned observability versions, checksum-verified agent, Compose overlay, scripts and expected outcomes below.'),
 ('Run tests on demand','Separate opt-in workflow: Run workflow or manually add the run-otel-e2e PR label; no push/build trigger.'),
 ('Keep handover current','This HTML is generated by '+file('scripts/render-poc-guide.py')+'; the manual workflow regenerates it and uploads it with results.')]))


section('value','Why OpenTelemetry helps this payment platform',p('The main demonstration is an investigation: take a payment ID, find its business log, follow the trace across services and asynchronous delivery, then use metrics to see whether the same problem affects other requests. The instrumentation turns separate service activity into evidence that developers and production support can navigate.')+
table(['Signal','What it tells you','What this PoC displays'],[
 ('Logs — events','What happened and which business operation it affected.','Payment outcome, risk decision, bank failure, outbox retry and notification events in Loki.'),
 ('Traces — one request','Where time was spent and which dependent operation failed. A span represents one operation; trace IDs connect related spans.','HTTP, JDBC, outbox.publish and RabbitMQ consumer spans in Tempo, with service, duration, status and parent relationships.'),
 ('Metrics — trends','How often something happens and whether latency, errors or resource usage are increasing.','HTTP rate/errors/p95, JVM memory, outbox publish attempts, service graph rates and telemetry target health in Prometheus/Grafana.')])+
p('OpenTelemetry generates, collects, processes and exports telemetry. In this PoC, Loki stores logs, Tempo stores traces, Prometheus stores metrics and Grafana displays them. Business log messages still come from application code; the Java agent captures them with service and active trace/span context. A healthy endpoint alone cannot establish that a payment or eventual notification succeeded.')+
table(['Investigation / advantage','Feature used','Practical result'],[
 ('Which service made this payment slow?','Request trace and operation durations','Inspect the bank HTTP client and JDBC spans before deciding which service to change.'),
 ('Why did payment return an unknown outcome?','Business outcome logs plus downstream error spans','Separate a bank decline from a timeout/500 that requires reconciliation; preserve the original idempotency ID.'),
 ('Payment succeeded; why is notification missing?','Persisted outbox context, producer/consumer spans, attempt metric and retry logs','Follow delivery after the HTTP response and identify a broker outage or consumer problem.'),
 ('Is one request slow, or are many requests affected?','Individual traces plus HTTP p95/rate/error metrics','Use the trace for a concrete example and aggregate metrics for the incident scope.'),
 ('HTTP is green but business outcomes are failing','Business event dashboard and risk/decline logs','Detect domain failures that HTTP 5xx graphs cannot describe.'),
 ('Are the dashboards empty because telemetry failed?','Prometheus targets, Collector health and Tempo ingestion rate','Investigate the observation pipeline before treating missing data as healthy behavior.'),
 ('What changed after a developer fix?','Comparable operation spans, logs and aggregate metrics','Check whether the measured bottleneck improved; this PoC has not measured an MTTR or capacity improvement.'),
 ('How can trace volume be reduced?','Optional tail sampling','Retain error/slow traces and probabilistically reduce normal traces. The recorded small sample verifies reduction, not an exact retention percentage.'),
 ('Can the backend change later?','Standard OTLP export and Collector routing','Application instrumentation is separated from backend routing; any backend replacement still requires its own integration validation.')])+
p('Read the screenshots as evidence: the operations dashboard shows a bank latency spike and HTTP 500 activity; the business dashboard shows completed, declined and reconciliation events; the telemetry dashboard shows outbox failure logs and its warning alert. The alert is visible in Prometheus/Grafana; pager delivery is not configured.')+
p('Concept references: ')+link('https://opentelemetry.io/docs/concepts/signals/','OpenTelemetry signals')+' · '+link('https://opentelemetry.io/docs/concepts/signals/logs/','Log correlation')+' · '+link('https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/configure-trace-to-logs/','Grafana trace/log navigation'))


section('instrumentation','Inside our microservices: how telemetry is generated',p('The integration begins at JVM startup, not inside Grafana. docker-compose.otel.yml mounts the checksum-verified Java agent into each of seven backend containers and supplies JAVA_TOOL_OPTIONS. The JVM loads the agent before the application; it instruments supported framework/library calls. Our observed HTTP, JDBC and RabbitMQ spans prove those library paths are instrumented. It does not trace every Java method or invent business outcomes.')+
code('JAVA_TOOL_OPTIONS=-javaagent:/otel/opentelemetry-javaagent.jar -Xms64m -Xmx384m\nOTEL_SERVICE_NAME=payment-service\nOTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318\nOTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf\nOTEL_TRACES_EXPORTER=otlp\nOTEL_METRICS_EXPORTER=otlp\nOTEL_LOGS_EXPORTER=otlp\nOTEL_PROPAGATORS=tracecontext,baggage\nOTEL_TRACES_SAMPLER=always_on\nOTEL_METRIC_EXPORT_INTERVAL=10000\nOTEL_INSTRUMENTATION_MICROMETER_ENABLED=true')+
table(['Signal / context','Generation inside the service','Observed output'],[
 ('Trace spans','The agent opens server/client spans around supported HTTP handling/calls, JDBC operations and messaging. Start/end times, status, attributes and parent IDs describe each operation.','A payment trace crosses edge, payment, customer, gateway, bank and notification services, including database spans.'),
 ('Trace propagation','Incoming W3C traceparent is extracted into an active Context; outgoing instrumented HTTP/message operations inject parent context. Each child has its own span ID under the trace ID.','Connected parent references across services, rather than unrelated records sharing only a business ID.'),
 ('Log records','Application code calls SLF4J/Logback with event=PAYMENT_COMPLETED or other business messages. Agent Logback instrumentation sends an OTel log record with active trace/span context and resource attributes.','The same application event appears in container console output and Loki; the OTel path sends records directly over OTLP, not by tailing the Docker log file.'),
 ('Metrics','The agent and enabled instrumentation produce HTTP duration histograms/counters and JVM measurements. The Micrometer bridge exposes compatible application instruments. Our explicit OTel Meter records outbox publish attempts with bounded outcome values.','HTTP/JVM series plus poc_outbox_publish_attempts_total{outcome="success|failure"}; the counter measures attempts, not unique committed payments.'),
 ('Resource identity','OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES identify service, namespace, environment and version.','service.name becomes service_name in the queryable backend representation; it lets support narrow a search.'),
 ('Export timing','Ended spans/logs are buffered and exported asynchronously; metrics are exported every 10 seconds here. Backend arrival and Prometheus scrape add delay.','A completed HTTP request may become visible in Grafana shortly afterward. Receiver health or an HTTP 200 alone is not proof that all telemetry is stored.'),
 ('Business meaning','Application logs, the outbox.publish span and the bounded publish-attempt instrument add domain context that library instrumentation cannot infer.','A reconciliation-required outcome can be investigated even when its public HTTP response is successful.')])+
'<h3>The durable outbox boundary needs explicit work</h3>'+p('The payment request and its outbox event are committed together. OutboxTraceContext captures only W3C traceparent/tracestate into nullable Flyway V6 columns. The later scheduler is a different execution context: OutboxRelay restores the saved parent, creates outbox.publish, makes it current, publishes through RabbitTemplate and waits for broker confirmation. Agent messaging instrumentation continues the producer/consumer context into Notification. The span ends in finally; failures record an exception/error status and a failure attempt. Legacy or invalid saved context creates a new root. Arbitrary baggage and credentials are not persisted.')+
code('request Context → outbox traceparent/tracestate columns\nscheduler → restore saved Context → outbox.publish.makeCurrent()\nRabbitTemplate publish → agent message propagation → notification consumer')+
p('X-Correlation-Id is our human-facing operational identifier. traceparent carries W3C trace/span context; they are different fields. A payment ID identifies the business transaction, while a trace ID identifies one related execution. Retries or reconciliation may create later executions, so keep the business ID and widen the time range.')+
p('The SDK represents a trace as spans grouped by Resource and instrumentation Scope. A resource identifies the JVM/service; a scope identifies the library emitting telemetry. OTel log records carry body/severity/timestamp/context fields; the console JSON wrapper is a separate output format. Metrics carry instrument names, units, attributes and timestamped number/histogram points. These structured objects become protobuf OTLP requests; Grafana never runs the Java instrumentation.')+
p('Repository implementation: ')+file('docker-compose.otel.yml')+' · '+file('scripts/setup-otel-agent.sh')+' · '+file('payment-service/src/main/java/com/srinu/payments/payment/outbox/OutboxTraceContext.java')+' · '+file('payment-service/src/main/java/com/srinu/payments/payment/outbox/OutboxRelay.java'))

section('collector-internals','Inside the Collector: receive, process, queue and export',p('The Collector is a separate Go process. Each JVM pushes an OTLP protobuf payload over HTTP to port 4318. The receiver exposes /v1/traces, /v1/metrics and /v1/logs, decodes the signal into the Collector’s telemetry representation and hands it to the corresponding configured pipeline. Port 4317 also accepts OTLP gRPC, although our JVM configuration uses HTTP/protobuf. The receiver does not scrape Java logs or magically inspect the application database.')+
table(['Pipeline stage in order','Our setting','What it does / boundary'],[
 ('OTLP receiver','0.0.0.0:4318 HTTP; 0.0.0.0:4317 gRPC','Accept and decode supported OTLP signal requests. Internal accepted/refused counters describe ingress; receiver acceptance is not a final backend acknowledgement.'),
 ('memory_limiter','Check every 1s; limit 384 MiB; spike allowance 96 MiB','Restrict processing under memory pressure. It can refuse incoming data; upstream retries/buffers have limits.'),
 ('resource','Upsert service.namespace=payment-poc','Apply common resource identity consistently before exporting.'),
 ('attributes/privacy + log transform','Trace/log pipelines delete authorization/workload-token/cookie attributes and selected database query text attributes; logs also redact selected secret-like body patterns','Remove the listed attributes. The log pipeline additionally redacts selected password/access-token/API-key/Bearer body patterns. Neither policy covers all PII or console output.'),
 ('Optional tail_sampling','Separate overlay; wait 30s; error policy, latency >2s, 10% probabilistic baseline','Buffer/decide on traces in memory. Disabled for deterministic main acceptance; enabled in a separate experiment. Multiple replicas require trace-aware routing for complete decisions.'),
 ('batch','Flush at 1s timeout or 512-item batch threshold','Group export work to reduce request overhead. Timeout is not an end-to-end freshness guarantee. This processor’s buffer remains in memory.'),
 ('Exporter queue','Tempo/Loki queues: 1000 queued requests; file_storage/queue on collector-data volume','Persist queued export requests, decouple slow backends and retry. Queue capacity, full/corrupt disk, retry expiry, agent loss and pre-queue buffers still permit data loss.'),
 ('Retry','Enabled; maximum elapsed retry window 5m','Retry eligible transient export failures. A permanent rejection is not repaired by retrying; inspect backend errors.'),
 ('Backend export','Tempo via OTLP gRPC; Loki via OTLP HTTP; Prometheus exposition endpoint','Signal-specific delivery paths below. Metrics use a scrape endpoint rather than the trace/log file queue.')])+
table(['Signal','Exact route in this PoC','Push or pull'],[
 ('Traces','JVM → Collector :4318/v1/traces → otlp/tempo → tempo:4317 → Tempo trace storage','Application and Collector push.'),
 ('Logs','JVM → Collector :4318/v1/logs → otlphttp/loki → loki:3100/otlp/v1/logs → Loki','Application and Collector push; exporter base endpoint is http://loki:3100/otlp and it appends the signal path.'),
 ('Application metrics','JVM → Collector :4318/v1/metrics → prometheus exporter at :8889/metrics → Prometheus scrape','JVM pushes; Prometheus pulls every 10 seconds.'),
 ('Trace-derived metrics','Tempo metrics-generator → Prometheus :9090/api/v1/write','Tempo pushes span metrics/service graphs by remote write; they reflect retained spans.'),
 ('Collector internal metrics','Collector telemetry reader → :8888/metrics → otel-collector-internal scrape job','Prometheus pulls the Collector’s own receiver/exporter/queue metrics. Port 8888 is distinct from application metrics on 8889.'),
 ('RabbitMQ metrics','rabbitmq_prometheus plugin → :15692/metrics/per-object → rabbitmq scrape job','Prometheus directly pulls broker queue/consumer metrics. These do not pass through the application OTLP pipeline.')])+
p('Collector queue storage runs as UID 10001. A one-shot volume initializer prepares permissions; it does not delete queued data. The crash experiment stops Tempo/Loki, queues a real payment’s telemetry, SIGKILLs/restarts the Collector, restores the backends, then requires the same connected trace and logs and a drained queue. Its observed result is in Evidence; configuration alone is not treated as a successful durability test.')+
p('Receivers decode OTLP into the Collector’s internal telemetry representation and invoke the configured pipeline in order. A successful OTLP response is not a receipt proving backend storage. The batch processor can accept data into memory before the persistent exporter queue; an abrupt crash can still lose that pre-queue data. File-backed queues improve recovery for requests already enqueued, and eligible failures are retried. Queue recovery is not an exactly-once telemetry guarantee.')+
p('Health endpoint :13133 reports Collector process availability. Internal metrics reveal whether it is accepting signals or failing exports. Logs are emitted as JSON to stderr for diagnosis without depending on Loki. There is no live automatic application-log file receiver or infinite retry queue.')+
p('Repository configuration: ')+file('observability/collector.yaml')+' · '+file('observability/collector-tail-sampling.yaml')+' · '+file('observability/prometheus.yaml')+' · '+file('observability/rabbitmq-enabled-plugins'))

section('query-lab','Backend storage, Grafana and a runnable query lab',p('Grafana queries provisioned datasources through its server-side proxy. It displays stored data; it does not generate application telemetry. Tempo returns trace/span data, Loki returns logs or log-derived counts, and Prometheus returns metric time series. Service graphs are derived from matching span relationships; they do not automatically prove every architectural dependency or a business outcome. Native OTLP Loki ingestion retains log attributes as structured metadata; service labels narrow streams while trace IDs are filtered as metadata.')+
table(['Backend','PoC persistence / retention','Important interpretation'],[
 ('Tempo','Local trace blocks/WAL on tempo-data; 24h retention','Trace waterfalls show overlapping operations and parent relationships. Do not sum overlapping spans or treat a sampled trace count as total traffic.'),
 ('Loki','Filesystem chunks/TSDB on loki-data; structured metadata; 24h retention','Search event text plus service/trace metadata. A missing record can mean time-range, ingest, sampling/context or retention issues.'),
 ('Prometheus','Local TSDB on prometheus-data; 24h retention; remote-write receiver enabled','Counters accumulate; rate/increase use a range and handle resets. Histogram p95 describes many observations, not one request.'),
 ('Grafana','Provisioned datasource/dashboard files plus grafana-data','Operations, business, pipeline and technical SLO dashboards; Explore queries; configured Loki trace links, Tempo log links and exemplar destinations.')])+
p('Start the stack first. In Grafana → Explore choose the datasource named below, switch to the code editor and run one query at a time over the request’s time range. Replace identifiers with those from the new run; archived trace IDs do not exist in a fresh backend. In Prometheus, the same PromQL can be run in its query UI. A valid empty result is different from a query error.')+
'<h3>Loki / LogQL: events, business IDs and trace correlation</h3>'+code('{service_name="payment-service"} |= "REPLACE_WITH_PAYMENT_ID"\n\n{service_name=~".+"} | trace_id="REPLACE_WITH_TRACE_ID"\n\n{service_name="payment-service"} |= "OUTBOX_PUBLISH_FAILED"\n\nsum(count_over_time({service_name="payment-service"} |= "event=PAYMENT_RECONCILIATION_REQUIRED" [5m]))')+
p('The first query finds the business transaction. Expand its log metadata to copy trace_id, then the second query joins service logs for that trace. The last query counts log events in a rolling five-minute window; it is not a durable count of unique transactions.')+
'<h3>Tempo / TraceQL: dependency errors and slow requests</h3>'+code('{ resource.service.name = "payment-service" }\n\n{ resource.service.name = "mock-bank-service" && status = error }\n\n{ resource.service.name = "mock-bank-service" && duration > 2s }')+
p('Search returns matching traces; select one to inspect the waterfall. For a known trace ID, paste its 32 hexadecimal characters into the Tempo query editor. Look at service, operation, status, duration, parent/child relationship and database/messaging attributes. Exemplar destinations are configured; this PoC has not separately asserted every exemplar-click path.')+
'<h3>Prometheus / PromQL: request trends and platform health</h3>'+code('sum by (service_name) (rate(http_server_request_duration_seconds_count[5m]))\n\nhistogram_quantile(0.95, sum by (le,service_name) (rate(http_server_request_duration_seconds_bucket[5m])))\n\nsum by (service_name) (rate(http_server_request_duration_seconds_count{http_response_status_code=~"5.."}[5m])) / clamp_min(sum by (service_name) (rate(http_server_request_duration_seconds_count[5m])), 0.001)\n\nsum(increase(poc_outbox_publish_attempts_total{outcome="failure"}[5m]))\n\nsum by (exporter) (otelcol_exporter_queue_size)\n\nsum(rate(otelcol_receiver_accepted_spans[5m]))\n\nrabbitmq_queue_messages_ready{queue="payments.notification"}\n\nrabbitmq_queue_consumers{queue="payments.notification"}\n\nrabbitmq_queue_messages_ready{queue="payments.notification.dlq"}\n\nup\n\nALERTS{alertstate="firing"}')+
p('The Prometheus exporter translates OTel instruments to Prometheus series, including normalized names/units and histogram bucket/count/sum series. Prometheus records each scrape in its TSDB. The graph range and query function determine the view: a counter value, an increase over time, a per-second rate, or a histogram quantile. Collector metrics exposition is not the same file-backed export path used for traces and logs.')+
p('Rates are per second; p95 is seconds; outbox increase is an extrapolated attempt count, not unique payments. Queue size/capacity are exporter requests here, not bytes or business events. Exporter-reported failures alone do not describe every retryable outage; compare queue growth, backend readiness and Collector logs. RabbitMQ ready and unacknowledged gauges distinguish waiting from in-flight delivery. HTTP 5xx excludes business failures returned inside HTTP 2xx. The explicit internal telemetry reader disables type/unit suffix additions, so these Collector metric names match this pinned configuration.')+
p('Dashboard definitions and datasource links: ')+file('observability/grafana/dashboards')+' · '+file('observability/grafana/provisioning/datasources/datasources.yaml'))

section('enterprise','How an enterprise would operate and extend this design',p('A production design keeps the instrumentation, collection, storage and investigation responsibilities explicit. The following is a deployment plan, not a claim that this single-node demo already provides cloud HA, identity or paging. A vendor-neutral collector boundary allows either self-hosted Grafana/Tempo/Loki/Prometheus-compatible storage or a managed backend after validating its authentication, limits and semantics.')+
table(['Production responsibility','Pattern to evaluate','Current PoC / next validation'],[
 ('Service ownership','Consistent service.name, namespace, environment and release version; owner/runbook labels; controlled semantic conventions','Resource identity and bounded operation/outcome dimensions are present. Add team ownership and release metadata through deployment configuration.'),
 ('Collection topology','Node/sidecar agents when host/file/container collection is needed; gateway collectors for centralized policy and routing','One gateway Collector here. On Kubernetes, decide gateway replicas, agent requirements, network policy and trace-aware routing before tail sampling.'),
 ('Security and privacy','Private ingress, TLS/mTLS or authenticated OTLP, managed secrets, backend tenancy/RBAC, least privilege and tested redaction','Local trusted-network demo credentials and loopback telemetry ports. Select IAM/secret/TLS strategy and test actual sensitive-data policies before using real data.'),
 ('Storage and continuity','Durable disks/objects, retention/cost budgets, HA backends, collector queue capacity/disk monitoring and recovery exercises','Named local volumes and persistent trace/log queues; live failure tests. Node/disk loss, corrupt storage, full queues and longer outages are not certified.'),
 ('SLO and incident policy','Business-success and user-latency SLIs; justified SLO windows; error-budget burn alerts; on-call ownership and deduplicated routing','HTTP/business/outbox/platform views and Prometheus warnings exist. Agree definitions/thresholds, then add Alertmanager or Grafana alert routing and verify delivery with the chosen channel.'),
 ('Cost and cardinality','Bounded resource/metric dimensions, retention tiers, span/log filtering and sampling policy aligned with investigations','Payment/account/user IDs are not custom metric dimensions. Assess per-object RabbitMQ cardinality at scale; sampled trace-derived metrics must not be used as total-request SLIs.'),
 ('Release quality','Normal build/tests plus deliberately invoked disposable integration/recovery checks; evidence bound to source revision','E2E remains manual-only. Include upgrade/config validation and compare actual series after instrumentation/backend version changes.'),
 ('Developer investigations','Start with the business ID, find correlated logs/trace, inspect downstream spans, compare aggregate trends, reproduce with idempotency','Worked cases and queries are provided. A trace can localize a delay/error but does not automatically prove source-code root cause.'),
 ('Future capabilities','Browser RUM, continuous profiling, Kubernetes/host/database infra metrics, SDK-based business SLIs and API-level security tests','Add after deciding a concrete investigation need, data policy and backend. These are explicitly not declared implemented by this increment.')])+
'<h3>Backend choices for a production rollout</h3>'+table(['Option','Integration to validate','Current status'],[
 ('Self-hosted Grafana stack','Keep OTLP routing to Tempo/Loki and Prometheus scraping; add the selected storage, identity, availability and retention architecture.','This PoC verifies the local single-node form.'),
 ('Mimir / managed metrics','A possible next design sends Prometheus metrics by remote_write to a Mimir-compatible endpoint and queries that endpoint from Grafana. Validate tenant/auth headers, ingestion limits, query semantics and outage recovery.','Documented extension; Mimir is not installed or tested here. '+link('https://grafana.com/docs/mimir/latest/send/','Official Mimir ingestion guide')),
 ('Grafana Cloud OTLP','Use the account-specific authenticated OTLP endpoint with secrets supplied through deployment configuration. Validate all signal mappings, resource identity, dashboards, retention, rate limits and export failures.','Requires a selected account/environment; no cloud integration is claimed. '+link('https://grafana.com/docs/opentelemetry/ingest/','Official OTLP ingestion guide')),
 ('Grafana Alloy','Evaluate this Collector distribution if its packaged collection/integration features suit the deployment. Migrate and revalidate configuration; do not assume it accepts our upstream YAML unchanged.','Alternative to evaluate, not a second collector installed in this PoC. '+link('https://grafana.com/docs/opentelemetry/collector/grafana-alloy/','Official Alloy guide'))
 ])+'<h3>Five-minute explanation you can give your manager</h3>'+bullets([
 'Our Java agent instruments supported calls inside each backend and exports three signals. Application events supply the business meaning.',
 'A W3C trace ID follows synchronous calls. We persist its parent context in the database outbox because notification delivery happens later on another thread/process.',
 'The Collector receives OTLP, applies common resource/privacy/memory/batch policy, then queues/exports traces and logs. Prometheus pulls exposed metrics.',
 'Tempo stores request traces, Loki stores event logs and Prometheus stores time series. Grafana queries them and connects an incident graph to related logs and spans.',
 'The manager demo follows a successful payment, a slow/error payment and a broker outage. We show the customer outcome, log evidence, responsible dependency, trend/alert and safe operational action.',
 'The manual suite verifies the real integrations and recovery behavior. Enterprise deployment adds identity, HA/storage, SLO ownership, cost controls and paging, each with its own acceptance gate.'
])+p('Authoritative reading: ')+link('https://opentelemetry.io/docs/zero-code/java/agent/','Java instrumentation')+' · '+link('https://opentelemetry.io/docs/collector/configuration/','Collector configuration')+' · '+link('https://opentelemetry.io/docs/collector/internal-telemetry/','Collector internal telemetry')+' · '+link('https://opentelemetry.io/docs/collector/resiliency/','Queue resiliency')+' · '+link('https://www.rabbitmq.com/docs/3.13/prometheus','RabbitMQ monitoring'))

log_examples=[]
log_files=sorted((ROOT/'artifacts').glob('logs-*.json'))
if log_files:
    capture=json.loads(log_files[0].read_text())
    for stream in capture.get('data',{}).get('result',[]):
        labels=stream.get('stream',{})
        for row in stream.get('values',[]):
            if any(event in row[1] for event in ('event=HTTP_REQUEST','event=OUTBOX_PUBLISHED')):
                log_examples.append({'timestamp_utc':datetime.datetime.fromtimestamp(int(row[0])/1e9,datetime.timezone.utc).isoformat(),'service_name':labels.get('service_name'),'severity_text':labels.get('severity_text'),'trace_id':labels.get('trace_id'),'span_id':labels.get('span_id'),'body':row[1]})
                break
        if len(log_examples)==2:break
example_trace=next((x['trace_id'] for x in log_examples if x.get('trace_id')), 'REPLACE_WITH_TRACE_ID')
log_body=p('A log row has a timestamp, severity, service, message and, when logged inside an active span, trace_id/span_id. service_name narrows the service; the business/payment ID identifies the operation; trace_id joins related service activity; span_id identifies the particular operation. Startup/background logs may have no active trace. Trace IDs are queried as structured metadata, rather than creating a Loki stream for every request.')
if log_examples:
    log_body+=p('Selected fields from actual captured Loki records, formatted for readability. These are observed application events, not invented demonstration logs. The evidence archive contains the complete response in '+log_files[0].name+'.')+code(json.dumps(log_examples,indent=2))
else:
    log_body+=p('No captured log response exists in this checkout. Run manual acceptance to populate actual record examples; the queries below describe how to investigate a fresh run.')
failure_examples=[]
failure_capture=read_artifact('recent-payment-logs.json', {})
seen=set()
for stream in failure_capture.get('data',{}).get('result',[]):
    labels=stream.get('stream',{})
    for row in stream.get('values',[]):
        for event in ('OUTBOX_PUBLISH_FAILED','PAYMENT_RECONCILIATION_REQUIRED'):
            if 'event='+event in row[1] and event not in seen:
                seen.add(event)
                failure_examples.append({'timestamp_utc':datetime.datetime.fromtimestamp(int(row[0])/1e9,datetime.timezone.utc).isoformat(),'service_name':labels.get('service_name'),'severity_text':labels.get('severity_text'),'trace_id':labels.get('trace_id'),'body':row[1]})
if failure_examples:
    log_body+='<h3>Actual failure log examples</h3>'+code(json.dumps(failure_examples,indent=2))+p('OUTBOX_PUBLISH_FAILED names the messaging failure and retry attempt. PAYMENT_RECONCILIATION_REQUIRED ties an uncertain bank outcome to a payment ID. These logs explain different operational problems; a generic error count cannot make that distinction.')
log_body+= '<h3>From payment ID to logs to trace</h3>'+bullets([
 'Start the local stack and create a small payment as demo / demo123. Copy its actual payment ID. Open Grafana on localhost:3001 and sign in as admin / otel-demo-admin.',
 'Choose Explore → Loki. Select a time window covering the request. Search the payment-service using the payment-ID query below. Expand a matching business log to read the event, outcome and trace_id.',
 'Use the configured Tempo link beside trace_id, or paste that trace ID into Explore → Tempo. Inspect the waterfall, each span’s service/status/duration and parent relationships. This validates an operation, rather than merely showing that containers are UP.',
 'Search all service logs using the same trace ID. Follow payment → gateway/bank/JDBC and the saved outbox.publish → RabbitMQ → notification path. Async delivery can finish after the HTTP response.',
 'Open the four dashboards to compare the particular request with request-rate, latency, business-outcome and outbox trends. A p95 panel is an aggregate over a time window, not the duration of the selected trace.'
])+code('{service_name="payment-service"} |= "REPLACE_WITH_PAYMENT_ID"\n\n{service_name=~".+"} | trace_id="'+example_trace+'"\n\n{service_name="payment-service"} |= "OUTBOX_PUBLISH_FAILED"\n\n{service_name="notification-service"} |~ "NOTIFICATION_(EVENT_RECEIVED|DUPLICATE_SKIPPED|RETRY_REUSED)"')
log_body+=p('The captured trace ID above belongs to the completed evidence run. That temporary stack was removed; its old records are in the evidence ZIP, not in a new local Tempo/Loki instance. For a new live demo, use the new payment and trace IDs. If a link has no result, check the time range, backend health and whether that trace was retained.')
log_body+='<h3>Where logs appear</h3>'+table(['View','What you see','When to use it'],[
 ('Grafana Explore → Loki','Searchable application events and service/trace metadata','Find a business operation and correlate its related logs.'),
 ('Operations dashboard → Correlated service logs','Logs for the selected service(s), alongside rate/p95/JVM metrics','Move from a symptom graph to relevant event details.'),
 ('Business dashboard','Outcome counts, notification activity and reconciliation/risk events','Investigate business failures even when HTTP responses are successful.'),
 ('Telemetry dashboard','Outbox failure events, retry attempts, alert state and scrape targets','Investigate delivery failures and telemetry availability.'),
 ('docker compose logs','Container console output, including startup and exporter errors','Diagnose failures when central telemetry is unavailable.'),
 ('Evidence ZIP','Raw Loki/Tempo/Prometheus responses and Compose logs from the passing run','Review the demonstration later, after the temporary services have stopped.')])
log_body+=code('bash scripts/otel-compose.sh logs -f payment-service gateway-service notification-service')
section('log-walkthrough','How logs appear and connect to a trace',log_body)

section('worked-cases','Worked investigations: what to show and why it matters',table(['Case to demonstrate','What appears in the UI / telemetry','What the evidence helps you decide'],[
 ('Successful payment and eventual notification','COMPLETED; PAYMENT_COMPLETED and OUTBOX_PUBLISHED events; connected HTTP/JDBC/outbox/Rabbit consumer spans; notification SENT.','Confirm both synchronous money movement and asynchronous delivery. The Evidence section records the connected trace’s observed span and service counts; authentication is a separate request.'),
 ('Insufficient funds / risk limit','Business decline or risk rejection in the application; corresponding business-event/risk panels and logs.','An HTTP-success response may contain a business FAILED result. Investigate the domain decision instead of escalating a server outage.'),
 ('Slow bank','RECONCILIATION_REQUIRED; gateway HTTP client error/timeout spans; elevated downstream latency; reconciliation logs.','The captured slow-failure trace contains an approximately five-second gateway client error span. Different deadlines can let downstream work outlive its caller. Preserve the original operation ID and investigate the ledger.'),
 ('Bank HTTP 500','Bank 500/error span; gateway fallback/unknown outcome; reconciliation events and HTTP-error activity.','Locate the failing dependency and distinguish uncertain money movement from a confirmed decline.'),
 ('Broker outage','Payment still commits; OUTBOX_PUBLISH_FAILED events and failure counter increase; warning alert; notification catches up after restart.','Identify delivery delay separately from payment failure. The live suite verified catch-up; do not create a duplicate payment.'),
 ('Collector outage','Payment remains available; agent/exporter errors can appear in container logs; a complete fresh trace is observed after restart/readiness recovery.','Separate a telemetry outage from an application outage. In-flight telemetry can be lost; missing logs are not evidence that a request never happened.'),
 ('Telemetry backend outage and Collector crash','Stop Tempo/Loki, observe queued export requests, complete a payment, kill/restart the Collector, restore backends and find the same trace and logs.','Distinguish durable exporter backlog from the application outbox. The live result records queue depth before the crash and confirms the backlog drained; disk/node loss and pre-queue buffers remain separate risks.'),
 ('Notification duplicate / poison payload','Real RabbitMQ integration tests verify one delivery for duplicate events and bounded retries ending in DLQ.','Investigate consumer deduplication/redrive safely. This is Testcontainers evidence; the four dashboard screenshots do not independently prove DLQ behavior.'),
 ('Tail sampling','A real bank error trace and seven-second slow trace are retained; normal traffic is reduced; full-trace Collector restored.','Understand retention/cost trade-offs. Sampled trace-derived rates are not total request counts; use application metrics for request-volume/SLO calculations.')])+
p('For the manager: demonstrate one successful payment, one slow/error payment and one broker outage. For each, show the user-facing outcome, the matching log, the trace/dependency responsible, the affected metric panel and the operational next step. The value is this connected investigation; a screenshot of a running server alone does not establish it.'))

services=[('Frontend',3000,'frontend','React customer screens, support/admin health and observability links','Browser → API Gateway'),('API Gateway',8088,'api-gateway','Routing, JWT/roles, correlation headers, operations health','Auth / Customer / Payment / Notification'),('Auth',8079,'auth-service','BCrypt-backed demo login, JWT issuance','PostgreSQL auth schema'),('Customer',8084,'customer-service','Customer profile and linked account','PostgreSQL customer schema'),('Payment',8080,'payment-service','Payment/P2P/refund, ownership, risk, reconciliation, outbox','Customer / Gateway / PostgreSQL / RabbitMQ'),('Gateway adapter',8081,'gateway-service','Bank HTTP client, timeout and circuit breaker','Mock Bank'),('Mock Bank',8082,'mock-bank-service','Simulated balances, debit/transfer/refund ledger and failure lab','PostgreSQL bank schema'),('Notification',8083,'notification-service','Consumer dedupe, retry/DLQ, simulated delivery','RabbitMQ / PostgreSQL notification schema')]
section('services','Services and end-to-end flow',table(['Service','Local port','Responsibility','Dependencies','Source'],[(name,str(port),purpose,deps,file(path)) for name,port,path,purpose,deps in services])+
p('Happy path: browser → API Gateway → Payment → Customer ownership check → Gateway adapter → Mock Bank → bank ledger. Payment state and outbox event are committed together. A scheduled relay restores saved W3C context, opens outbox.publish, sends via RabbitMQ and waits for publisher confirm. Notification consumes and persists a deduplicated simulated delivery.')+
p('The relay keeps traceparent and tracestate in nullable V6 migration columns. Existing events without context create new roots. Baggage is deliberately not persisted. Agent instrumentation handles HTTP, JDBC and messaging; only the durable scheduling boundary needs explicit context restoration. Retries after long outages can appear later than the original request, so widen the trace/log time window.')+
p('Telemetry path: every Java process exports OTLP/HTTP → Collector. Traces go to Tempo; logs to Loki native OTLP; application metrics are exposed by the Collector for Prometheus scraping. Tempo produces span metrics and service graphs into Prometheus via remote write. Grafana reads all three backends.'))

section('start','Recreate locally',p('Convenience commands: bash scripts/run-poc.sh start builds and starts the demo; test runs live business/telemetry/resilience checks; report refreshes evidence; stop shuts down; reset deletes this disposable project’s state. Browser screenshots are captured by the GitHub manual workflow.')+p('Prerequisites: Git, Java 21, Maven, Docker with Compose v2, Python 3, curl, jq and sha256sum. Allow roughly 12 GB RAM for a comfortable local demo. Containers and dependencies need internet access on first build. Use a fresh disposable stack for deterministic tests; fixed smoke-test IDs and bank balances make reusing old state unsuitable.')+
code('''git clone https://github.com/srinu7893/otel-payment-platform-poc.git
cd otel-payment-platform-poc
# Before merge, select the implementation branch:
git checkout feature/otel-observability-manual-e2e
export COMPOSE_PROJECT_NAME=otel-demo
mvn -B clean verify
bash scripts/setup-otel-agent.sh
bash scripts/otel-compose.sh config --quiet
bash scripts/otel-compose.sh run --rm --no-deps otel-storage-init
bash scripts/otel-compose.sh run --rm --no-deps otel-collector validate --config=/etc/otelcol/config.yaml
bash scripts/otel-compose.sh run --rm --no-deps --entrypoint promtool prometheus check config /etc/prometheus/prometheus.yml
bash scripts/otel-compose.sh up --build -d
bash scripts/e2e/wait-ready.sh''')+
p('Backend Dockerfiles copy packaged target/*.jar; building with Maven first is required. The frontend container builds its own bundle. Starting without docker-compose.otel.yml keeps the original baseline agent-free.')+
table(['Destination','Link / demo login'],[
 ('Customer / Support UI',link('http://localhost:3000','http://localhost:3000')+' · demo / demo123 or support / support123'),
 ('Grafana dashboards',link('http://localhost:3001/d/payment-poc','Payment operations')+' · admin / otel-demo-admin (override GRAFANA_ADMIN_PASSWORD before startup)'),
 ('Grafana pipeline dashboard',link('http://localhost:3001/d/telemetry-pipeline','Telemetry pipeline health')),
 ('Grafana business dashboard',link('http://localhost:3001/d/payment-business','Business events and reconciliation')),
 ('Prometheus',link('http://localhost:9090','Queries, targets and alert rules')),
 ('Tempo readiness',link('http://localhost:3200/ready','Trace backend health')),
 ('Loki readiness',link('http://localhost:3100/ready','Log backend health')),
 ('Collector readiness',link('http://localhost:13133','Collector health')),
 ('RabbitMQ',link('http://localhost:15672','Queues / DLQ')+' · payments / payments'),
 ('API contract',link('http://localhost:8088/swagger-ui.html','Swagger UI')+' · '+file('docs/openapi-baseline.yaml'))])+
p('New telemetry ports bind to loopback. Existing application/database/broker ports still use the baseline bindings: this is a trusted local demo, not an internet-facing deployment. Remote use requires ingress/auth/TLS and frontend VITE_GRAFANA_URL configuration.')+
code('''# Stop without deleting telemetry volumes:
bash scripts/otel-compose.sh down
# Reset only this disposable demo (deletes its telemetry volumes and demo state):
bash scripts/otel-compose.sh down -v --remove-orphans'''))

section('tests','Manual automated acceptance',p('GitHub → Actions → manual-otel-e2e → Run workflow. Select the intended ref and choose whether to include broker/Collector outages. Before merge, manually add the run-otel-e2e label to the same-repository PR. Remove/re-add the label for a new run. The Run workflow button becomes available once workflow_dispatch exists on the default branch. Ordinary CI retains backend tests and build validation, but does not start the stack or run E2E.')+
p('For local testing, keep the same COMPOSE_PROJECT_NAME used at startup. The resilience option stops only that Compose project’s demo broker/Collector. Run scripts in this order on fresh state:')+
code('''bash scripts/e2e/business-smoke.sh
RESILIENCE=true python3 scripts/e2e/otel_acceptance.py
bash scripts/pre_otel_acceptance.sh
python3 scripts/e2e/live-traffic.py
python3 scripts/e2e/advanced-sampling.py
python3 scripts/e2e/capture-evidence.py
python3 scripts/render-poc-guide.py''')+
p('The manual workflow runs Maven unit and Testcontainers integration tests, validates backend configs, builds/starts the stack, checks business success/failure paths, queries real telemetry backends, collects diagnostic logs and always removes its disposable stack. Evidence artifact: otel-poc-evidence-<run number>. Includes Surefire reports, actual OTel assertion results, trace ID summary, Compose logs and this HTML. A failed test fails the workflow; missing telemetry is not treated as a skipped success.')+
table(['Scenario','Expected result','Executable source'],[
 ('Login, payment, P2P and refund','COMPLETED; expected notification becomes SENT; refund ties to original payment',file('scripts/e2e/business-smoke.sh')),
 ('Payment/refund replay','Same original IDs; bank integration verifies one balance change',file('scripts/e2e/business-smoke.sh')+' / '+file('mock-bank-service/src/test/java/com/srinu/payments/bank/integration/BankPostgresIntegrationTest.java')),
 ('Insufficient funds','Business FAILED response; distinguish from HTTP/server failure',file('scripts/e2e/business-smoke.sh')),
 ('Risk rejection','HTTP 422 + RISK_LIMIT_EXCEEDED / MAX_TRANSACTION_AMOUNT',file('scripts/e2e/business-smoke.sh')),
 ('Authentication and role failures','401 for no token / invalid login; 403 for customer operations route / wrong source account',file('scripts/e2e/otel_acceptance.py')),
 ('Slow bank / simulated bank 500','RECONCILIATION_REQUIRED plus an actual downstream error trace; never blindly retry money movement',file('scripts/e2e/otel_acceptance.py')+' / '+file('scripts/pre_otel_acceptance.sh')),
 ('HTTP + JDBC + outbox + Rabbit consumer trace','One trace has six required service names, DB spans, outbox.publish and valid parent references',file('scripts/e2e/otel_acceptance.py')),
 ('Metrics/log integration','Seven service HTTP metric series, JVM and custom outbox metric, service graph; exact payment trace ID in Loki',file('scripts/e2e/otel_acceptance.py')),
 ('Advanced tail sampling','Real bank 500 and seven-second traces retained; normal traffic reduced; restores full-trace Collector afterward',file('scripts/e2e/advanced-sampling.py')),
 ('Broker outage and recovery','Payment commits; outbox failure metric appears; notification catches up after broker restarts',file('scripts/e2e/otel_acceptance.py')),
 ('Persistent queue/backend outage','Real queued payment trace and matching logs survive Collector SIGKILL/restart while Tempo/Loki are down; backlog drains after recovery',file('scripts/e2e/otel_acceptance.py')),
 ('Collector outage and recovery','Payment remains available; a fresh trace reaches Tempo after restart. No promise of lossless outage telemetry.',file('scripts/e2e/otel_acceptance.py')),
 ('Poison event and redelivery','Bounded retries → DLQ with x-death; duplicate event results in one delivery',file('notification-service/src/test/java/com/srinu/payments/notification/integration/NotificationRabbitIntegrationTest.java')),
 ('Saved context / legacy event','W3C trace ID, span ID and tracestate survive scheduler boundary; invalid context cannot inherit scheduler trace',file('payment-service/src/test/java/com/srinu/payments/payment/outbox/OutboxTraceContextTest.java'))]))

section('demo','Manual manager demonstration',bullets([
 'Open the customer UI and sign in as demo / demo123. Create a small merchant payment using ACC1001. Note its payment ID and confirm COMPLETED.',
 'Sign in as support / support123 in another browser session. Open the operations dashboard and verify service health. Use the Observability card to open Grafana.',
 'In Grafana Explore choose Loki and search '+code('{service_name="payment-service"} |= "PAYMENT_ID"')+'Replace PAYMENT_ID with the actual ID. Expand the log metadata; open trace_id in Tempo. Follow edge → payment → customer/gateway → bank → JDBC, then outbox.publish → RabbitMQ → notification.',
 'Explain request duration versus eventual notification delay. The async consumer can finish after the HTTP response. Examine parent spans, database duration and service map rather than summing overlapping durations.',
 'Refund the completed payment. Check refund history and PAYMENT_REFUNDED notification. Replay via the smoke script and explain bank-side idempotency and consumer deduplication.',
 'Use amount 6000 on a fresh ACC1001 balance to demonstrate insufficient funds. Use 100001 for configured transaction-risk rejection. Explain why a business failure can return HTTP 2xx and why HTTP error graphs alone are insufficient.',
 'Use slowdemo / slowdemo123 with ACC-SLOW and errordemo / errordemo123 with ACC-ERROR for timeout/500 scenarios. Confirm reconciliation state, inspect downstream error/latency spans and distinguish unknown outcome from decline.',
 'Run the optional resilience suite. Show outbox failure counters and recovery after broker restart. Show application availability during Collector outage, then fresh traces after recovery.',
 'Finish with the workflow evidence artifact and Evidence section below. Demonstrate passed assertions from an actual run; label any unexecuted scenario explicitly.'
]))

section('support','Support and developer runbooks',table(['Symptom','Investigation','Safe action'],[
 ('Payment seems stuck','Look up business ID in support UI; search corresponding log → trace. Inspect gateway timeout, bank ledger and reconciliation logs.','Keep original payment/idempotency ID. Do not create a replacement payment while the outcome is unknown.'),
 ('HTTP looks healthy but payments fail','Use PAYMENT_NOT_COMPLETED and PAYMENT_RECONCILIATION_REQUIRED log events; inspect risk/bank decisions.','Separate business rejection from transport failure; use the documented reconciliation path.'),
 ('Notification missing','Check outbox status/retry logs; inspect payments.notification and DLQ; follow producer/consumer spans.','Restore broker first. Investigate poison payload before deliberate redrive; preserve event ID for dedupe.'),
 ('Dashboard empty','Prometheus Targets → otel-applications; check Collector logs, OTLP endpoint, agent mount and service.name. Query metrics directly.','Verify actual series names and selected time window; do not equate empty data with zero errors.'),
 ('Logs absent but traces exist','Check Collector logs pipeline, Loki /ready, native OTLP configuration and structured metadata.','Check Logback instrumentation and widen log time range. Do not enable credential/header dumping.'),
 ('Trace fragments','Inspect saved outbox traceparent and publisher/consumer spans. Check late retries and sampling settings.','Use unsampled acceptance mode; delayed outbox traces may arrive after sampling decisions.'),
 ('Slow request','Compare HTTP p95 to individual spans, JDBC time, JVM memory and downstream bank latency.','Optimize the measured bottleneck; keep bounded timeouts and money-movement idempotency.')])+
p('Developers add business spans around meaningful work using the OpenTelemetry API supplied by the agent; do not install a second SDK or tracing starter alongside it. Use bounded dimensions such as outcome and operation. Never use payment IDs, account numbers, email, JWT or raw URL values as metric labels. The custom outbox metric counts publish attempts confirmed by the broker, not unique committed payments; database rollback and retry can increase it.')+
code('''# Loki: operational failures
{service_name="payment-service"} |~ "PAYMENT_(NOT_COMPLETED|RECONCILIATION_REQUIRED)"
# Loki: exact known trace
{service_name=~".+"} | trace_id="REPLACE_WITH_TRACE_ID"
# Tempo TraceQL: bank errors
{ resource.service.name = "mock-bank-service" && status = error }
# Prometheus: HTTP p95 (seconds)
histogram_quantile(0.95, sum by (le,service_name) (rate(http_server_request_duration_seconds_bucket[5m])))
# Prometheus: outbox publish failures
sum(increase(poc_outbox_publish_attempts_total{outcome="failure"}[5m]))'''))

section('cloud','Cloud Run architecture, production support and BigQuery',
    render_markdown((ROOT/'docs/CLOUD_RUN_PLAN.md').read_text())+
    '<h3>BigQuery query templates</h3>'+code((ROOT/'deploy/bigquery/queries.sql').read_text())+
    p('Repository implementation: ')+file('.github/workflows/manual-cloud-run.yml')+' · '+file('.github/workflows/manual-cloud-acceptance.yml')+' · '+file('deploy/cloud-run')+' · '+file('scripts/cloud')+' · '+file('cloud-runtime'))

privacy=read_artifact('privacy-results.json', {})
section('support-increment','SLO, privacy and support verification',
    p('The payment-slo Grafana dashboard adds six panels for technical availability, latency <=2.5 seconds, 5m/1h budget burn, request rate and alert state. It uses HTTP server metrics independently of trace sampling. The target and burn threshold are demonstration choices; business completion is a separate outcome and no pager destination is configured.')+
    table(['Check','Recorded result / boundary'],[
        ('Synthetic stored-log privacy test', e(privacy.get('status','Not recorded in this evidence snapshot'))+' — only Collector-exported log bodies; stdout and complete PII redaction remain outside this check.'),
        ('SLO alert scenarios', e(pipeline.get('SLO rule scenarios','Not recorded in this evidence snapshot'))+' — deterministic healthy/no-traffic/2% 5xx rule evaluation, not a production incident trial.'),
        ('Cloud container/config contracts', e(pipeline.get('Cloud asset validation','Not recorded in this evidence snapshot'))+' — image/config build checks without cloud authentication; not a live GCP deployment.'),
        ('Live GCP and BigQuery', 'Not executed in this local evidence snapshot. Configure the isolated GCP environment and run the two separate cloud workflows.')])+
    (code('\n'.join(privacy.get('storedLines',[]))) if privacy else '')+
    p('Manual drill sources: ')+file('scripts/e2e/privacy_acceptance.py')+' · '+file('observability/slo-rule-tests.yaml')+' · '+file('observability/grafana/dashboards/payment-slo.json'))

section('new-support','Durable business state, alert delivery and synthetic journey',render_markdown((ROOT/'docs/SUPPORT_ENHANCEMENTS.md').read_text()))

section('coverage','OpenTelemetry coverage: basic to advanced' ,table(['Capability','This increment','Boundary / remaining work'],[
 ('Instrumentation','Java agent attached to all seven backend JVMs; HTTP/JDBC/RabbitMQ/JVM; Micrometer bridge enabled','Browser RUM, continuous profiling, host/Kubernetes metrics are not implemented; RabbitMQ queue-depth/consumer metrics are added in this increment.'),
 ('Signals and context','Traces, metrics, logs, W3C propagation, durable outbox context, trace/log links','Global baggage propagation is available; arbitrary baggage is not stored in outbox.'),
 ('Business observability','Custom outbox.publish span and attempt metric; business outcome log panels','No full custom payment SLO/error-budget instrumentation or complete domain audit store.'),
 ('Collector','OTLP gRPC/HTTP receivers; resource, memory limit, privacy attribute deletion, batching, bounded exporter queues/retry','Trace/log exporter queues use file_storage on a named volume; receiver/batch/tail-sampler buffering, agent buffers, queue capacity, disk failure and retry expiry still permit loss.'),
 ('Visualization','Provisioned operations, business, pipeline and technical SLO dashboards; trace search, service graph, exemplars configured','The Evidence section records rendered dashboards and backend queries. Exemplars depend on sampled data and compatible panels.'),
 ('Sampling','Default always_on for deterministic demo; isolated tail experiment retains errors/slow traces + 10% baseline','The manual workflow runs a separate real-request sampling experiment after deterministic full-trace E2E. Error/slow rules require all spans for a trace to reach one sampling Collector.'),
 ('Alerts','Prometheus rules for telemetry scrape failure, outbox failure, span error ratio, Collector queue pressure/export failures, notification backlog and DLQ','Local Alertmanager routing/inbox delivery now have manual acceptance; real pager/email delivery and production SLO policy remain unconfigured.'),
 ('Resilience','Business idempotency/reconciliation plus broker/Collector outage tests','Not a load, capacity, HA, disaster recovery or production-readiness certification.'),
 ('Security/privacy','No authorization/cookie capture; selected sensitive DB attributes removed; bounded metric labels','Existing logs contain synthetic customer/business data. Attribute deletion does not sanitize arbitrary log bodies. Review/redact before using real data.'),
 ('Deployment','Local Compose plus Cloud Run IAM/runtime/container/manual release assets; optional BigQuery SQL','Cloud account provisioning, durable data services, live deployment/acceptance, HA/backups and cloud datasource validation remain pending.')])+
p('Optional sampling experiment (do not run deterministic trace assertions with it enabled):')+
code('''docker compose -f docker-compose.yml -f docker-compose.otel.yml -f docker-compose.sampling.yml \
  run --rm --no-deps otel-collector validate --config=/etc/otelcol/config.yaml --config=/etc/otelcol/tail.yaml
docker compose -f docker-compose.yml -f docker-compose.otel.yml -f docker-compose.sampling.yml up -d otel-collector
# After experimentation, restore full-trace acceptance configuration:
bash scripts/otel-compose.sh up -d --force-recreate otel-collector''')+
p('Tail sampling waits 30 seconds and retains errors, latency over 2 seconds, and a 10% baseline. Late outbox retries can exceed this decision window; evaluate span links or a larger window before production. Service-graph/span-rate metrics derived after sampling describe sampled traffic, not total traffic; use unsampled application metrics for accurate request SLOs.'))

section('findings','Review findings and remaining decisions',bullets([
 '<strong>Fixed:</strong> transaction outbox lacked durable trace context. V6 adds nullable traceparent/tracestate and the relay restores request context around publish.',
 '<strong>Fixed:</strong> full-stack smoke and pre-OTel acceptance ran on ordinary CI. They now live in a manual-only workflow, along with telemetry and resilience assertions.',
 '<strong>Fixed after live testing:</strong> async React form reset, browser locale, Loki all-service selection, Collector recovery readiness, customer notification filter/pagination correctness, Grafana lower-panel lazy rendering and the OpenAPI curl pipe race; repeated manual runs capture these behaviors.',
 '<strong>Fixed:</strong> no telemetry backends or operational trace/log entry point. The overlay provisions all three signal paths and support UI links.',
 '<strong>Known baseline boundary:</strong> internal customer/bank endpoints rely on trusted-network deployment; demo JWT secrets/accounts and exposed service ports must not be deployed publicly. See '+file('docs/SECURITY_BASELINE.md')+' and '+file('docs/SERVICE_IDENTITY_STRATEGY.md')+'.',
 ('<strong>Verified live:</strong> agent/library compatibility, backend configurations, connected payment traces, metrics/logs, recovery scenarios, browser screens, four rendered dashboards and tail sampling passed in the recorded manual run.' if verified else '<strong>Verification gate:</strong> check recorded workflow outcomes and assertion results below. Only a fully passing run verifies the live integration.'),
 '<strong>Production scope:</strong> choose GCP accounts/storage/live acceptance, backend/vendor, IAM/secrets, retention/cost, broker management and support escalation policy. All OpenTelemetry ecosystem features cannot meaningfully be declared complete by one local PoC.'
]))

evidence=p('Live integration status: '+('VERIFIED — every recorded workflow stage and acceptance assertion passed.' if verified else 'See individual recorded outcomes; full live verification is not established by source configuration alone.'))
evidence+=p('Tested application source revision: '+revision+'; source ref: '+ref+'. Generated '+datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')+'.')
evidence+=p('Reproduce this exact source snapshot with git checkout '+revision+' before building. Source links follow the implementation branch; the revision above identifies the tested snapshot.')
if os.environ.get('GITHUB_RUN_ID'):
    evidence+=p('GitHub run: ')+link('https://github.com/'+os.environ['GITHUB_REPOSITORY']+'/actions/runs/'+os.environ['GITHUB_RUN_ID'],'Open exact workflow run')
if test_totals['tests']:
    evidence+=table(['Backend tests','Failures','Errors','Skipped'],[tuple(str(test_totals[k]) for k in ('tests','failures','errors','skipped'))])
if pipeline:
    evidence+=table(['Workflow stage','Actual outcome'],[(e(k),e(v)) for k,v in pipeline.items()])
if results:
    evidence+=table(['Telemetry/security/resilience assertion','Actual result','Detail'],[(e(x['scenario']),e(x['status']),e(x.get('error',str(x.get('seconds',''))+' seconds'))) for x in results])
else:
    evidence+='<div class="notice">NOT RUN HERE: no live OTel acceptance result file is present. Docker was unavailable in the authoring workspace; backend tests and live telemetry must be verified in the manual workflow. Do not interpret this guide as a successful runtime test report.</div>'
trace=read_artifact('trace-evidence.json', {})
if trace:
    evidence+='<h3>Connected payment trace</h3>'+code(json.dumps(trace,indent=2))
targets=read_artifact('prometheus-targets.json', {}).get('data',{}).get('activeTargets',[])
if targets:
    evidence+=table(['Prometheus target','Observed health'],[(e(x['labels'].get('job','')),e(x['health'])) for x in targets])
metric_names=read_artifact('prometheus-series.json', {}).get('data',[])
if metric_names:
    evidence+=p(str(len(metric_names))+' metric names exposed across the application and telemetry backends; the acceptance suite separately asserts required application, JVM, outbox and service-graph series.')
alerts=read_artifact('prometheus-alerts.json', {}).get('data',{}).get('alerts',[])
if alerts:
    evidence+=table(['Recorded alert','Observed state'],[(e(x['labels'].get('alertname','')),e(x['state'])) for x in alerts])
for title, data in [('Browser acceptance',browser),('Measured demonstration traffic',traffic),('Advanced tail-sampling experiment',sampling),('Persistent export queue recovery',read_artifact('persistent-queue.json',{})),('Synthetic journey',synthetic),('Durable state and incident lifecycle',support_results)]:
    if data:
        evidence+='<h3>'+e(title)+'</h3>'+code(json.dumps(data,indent=2))
screen_captions={
 '01-customer-overview':'Customer overview: the entry point for producing a real payment and its telemetry.',
 '02-browser-payment-completed':'Payment completed: the customer outcome to correlate with PAYMENT_COMPLETED, bank spans and eventual notification.',
 '03-browser-transfer-completed':'Transfer completed: the P2P customer flow exercised by the browser.',
 '04-support-operations':'Support view: live service health, problem payments and notification activity; use IDs to investigate the corresponding telemetry.',
 '09-incident-inbox':'Local Alertmanager delivery into the incident inbox; acknowledgement and resolved lifecycle are verified in the separate support acceptance.',
 '05-payment-poc':'Operations dashboard: locate the bank latency/error spike, compare request/JVM trends and read correlated service logs.',
 '06-payment-business':'Business dashboard: distinguish completed payments, declines and unknown outcomes; inspect notification and reconciliation/risk events.',
 '08-payment-slo':'Technical SLO dashboard: unsampled HTTP availability/latency and error budget trends; example targets, not a business completion guarantee.',
 '07-telemetry-pipeline':'Telemetry health: scrape targets, Collector ingress/export queues, RabbitMQ depth/consumers/DLQ, Tempo ingestion and outbox retry/failure activity.'
}
screens=sorted((ROOT/'artifacts/screenshots').glob('*.png')) if os.environ.get('POC_EMBED_SCREENSHOTS','true').lower()=='true' else []
if screens:
    evidence+='<h3>Captured from the live run</h3>'+p('Browser captures use Asia/Kolkata (UTC+05:30); log examples and the generation timestamp use UTC. Align the query time window/timezone when comparing screenshots with raw records.')+''.join('<figure><figcaption>'+e(screen_captions.get(f.stem,f.stem))+'</figcaption><img style="max-width:100%;border:1px solid #ccd" alt="'+e(f.stem)+'" src="data:image/png;base64,'+base64.b64encode(f.read_bytes()).decode()+'"></figure>' for f in screens)
section('evidence','Execution evidence',evidence+p('Backend Surefire reports, raw trace/log/metric responses, database summaries, Compose logs and screenshots are included in the downloadable evidence archive. Frontend/container build results are recorded in ordinary CI and linked from the pull request. A workflow artifact is a snapshot of that run, not a permanent promise of current health. The manual guide and scenario table describe expected outcomes; this section records observed results only.'))

sources=[('OTel Java agent','https://opentelemetry.io/docs/zero-code/java/agent/'),('Agent configuration','https://opentelemetry.io/docs/zero-code/java/agent/configuration/'),('Custom API with agent','https://opentelemetry.io/docs/zero-code/java/agent/api/'),('Collector configuration','https://opentelemetry.io/docs/collector/configuration/'),('Loki native OTLP ingestion','https://grafana.com/docs/loki/latest/send-data/otel/'),('Tempo service graphs','https://grafana.com/docs/tempo/latest/metrics-from-traces/service_graphs/'),('Tail sampling processor','https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor'),('Manual GitHub workflows','https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow')]
section('sources','Source links and maintenance',table(['Item','Repository source'],[(e(label),file(path)) for label,path in [('Base stack','docker-compose.yml'),('OTel overlay','docker-compose.otel.yml'),('Collector','observability/collector.yaml'),('Tempo','observability/tempo.yaml'),('Loki','observability/loki.yaml'),('Prometheus / alerts','observability/prometheus.yaml'),('Dashboard JSON','observability/grafana/dashboards'),('Datasource links','observability/grafana/provisioning/datasources/datasources.yaml'),('Manual workflow','.github/workflows/manual-otel-e2e.yml'),('Acceptance scripts','scripts/e2e'),('HTML generator','scripts/render-poc-guide.py')]])+
bullets([link(url,title) for title,url in sources])+
p('When changing service topology, telemetry config or scenario behavior, update the generator’s capability/scenario tables in the same change. Run python3 scripts/render-poc-guide.py and commit the regenerated docs/POC_GUIDE.html. After each manual run, download the refreshed HTML and evidence artifact. Results are never silently promoted to passed.'))
nav=''.join('<a href="#'+key+'">'+e(title)+'</a>' for key,title,_ in sections)
body=''.join('<section id="'+key+'"><h2>'+e(title)+'</h2>'+content+'</section>' for key,title,content in sections)
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Payment Platform · OpenTelemetry POC guide</title><style>
:root{color-scheme:light;--ink:#142e3e;--accent:#007c83}*{box-sizing:border-box}body{margin:0;background:#f2f6f8;color:var(--ink);font:16px/1.6 system-ui,sans-serif}header{background:#123546;color:white;padding:48px max(5vw,24px)}header h1{max-width:1000px;margin:8px 0;font-size:clamp(30px,4vw,48px);line-height:1.15}header p{color:#cae4e9}main{max-width:1280px;margin:auto;padding:24px}nav{display:flex;flex-wrap:wrap;gap:8px;padding-bottom:16px}nav a{background:white;padding:7px 12px;border-radius:6px;font-size:13px}section{background:white;border:1px solid #dde7ec;border-radius:10px;padding:28px;margin:20px 0;scroll-margin-top:16px}h2{font-size:26px;margin:0 0 18px;color:#12475c}a{color:#006e82;overflow-wrap:anywhere}pre{background:#102c3c;color:#e1f5ee;padding:18px;border-radius:7px;overflow:auto;font:13px/1.6 ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th{text-align:left;background:#eaf3f5}th,td{padding:12px;border-bottom:1px solid #dce7ec;vertical-align:top}li{margin:12px 0}.notice{background:#fff3d5;border-left:5px solid #d18a00;padding:18px;font-weight:600}.tag{letter-spacing:.14em;text-transform:uppercase;font-size:12px;color:#9ce0dd}@media print{body{background:white;font-size:11px}header{padding:20px}nav{display:none}main{padding:0}section{break-inside:auto;border:0;padding:12px}h2{break-after:avoid}tr{break-inside:avoid}pre{color:#102c3c;background:#f2f6f8}}@media(max-width:600px){main{padding:10px}section{padding:16px}th,td{padding:8px;min-width:130px}}
</style></head><body><header><div class="tag">Engineering / Support / Manager handover</div><h1>Payment Platform<br>OpenTelemetry POC</h1><p>Understand the value. Follow a payment from logs to traces. Verify the evidence.</p></header><main><nav>'''+nav+'</nav>'+body+'</main></body></html>'
(ROOT/'docs/POC_GUIDE.html').write_text(html)
print('Generated docs/POC_GUIDE.html')
