#!/usr/bin/env python3
"""Regenerate the self-contained manager/support guide from repository configuration and run evidence."""
from pathlib import Path
from html import escape as e
import base64
import datetime
import json
import os
import subprocess
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
os.chdir(ROOT)

def git(*args):
    return subprocess.check_output(['git', *args], text=True).strip()

revision=os.environ.get('POC_EVIDENCE_REVISION') or git('rev-parse','HEAD')
ref=os.environ.get('GITHUB_HEAD_REF') or os.environ.get('GITHUB_REF_NAME') or git('branch','--show-current') or 'main'
source='https://github.com/srinu7893/otel-payment-platform-poc/blob/'+ref+'/'
def read_artifact(name, default=None):
    path=ROOT/'artifacts'/name
    return json.loads(path.read_text()) if path.exists() else default

results=read_artifact('otel-results.json', [])
pipeline=json.loads(os.environ.get('POC_PIPELINE_OUTCOMES','{}'))
browser=read_artifact('browser-results.json', {})
traffic=read_artifact('traffic.json', {})
sampling=read_artifact('advanced-sampling.json', {})
test_totals={k:0 for k in ('tests','failures','errors','skipped')}
for path in ROOT.glob('**/target/surefire-reports/TEST-*.xml'):
    suite=ET.parse(path).getroot()
    for key in test_totals:
        test_totals[key]+=int(suite.attrib.get(key,0))
verified=bool(results) and all(x['status']=='PASS' for x in results) and browser.get('status')=='PASS' and sampling.get('status')=='PASS' and bool(pipeline) and all(x=='success' for x in pipeline.values())
sections=[]
def section(key,title,body):
    sections.append((key,title,body))
def p(text): return '<p>'+e(text)+'</p>'
def code(text): return '<pre><code>'+e(text)+'</code></pre>'
def link(url,label): return '<a href="'+e(url,quote=True)+'">'+e(label)+'</a>'
def file(path,label=None): return link(source+path,label or path)
def table(headers,rows):
    return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+e(x)+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def bullets(items): return '<ul>'+''.join('<li>'+x+'</li>' for x in items)+'</ul>'

section('summary','Manager overview',p('A simulated payment platform demonstrating synchronous HTTP calls, database transactions, durable asynchronous delivery and OpenTelemetry across seven Java services. No real money, bank, SMS or email providers are involved.')+
p('This increment implements the local observability stack and executable acceptance gates. Configuration and source presence do not prove runtime success: use the Evidence section to see what actually ran. GCP deployment and production hardening remain separate decisions.')+
table(['Outcome','Implementation / acceptance'],[
 ('Follow a payment end to end','Java agent → HTTP/JDBC spans → persisted outbox trace context → RabbitMQ consumer; asserted by a single connected trace in Tempo.'),
 ('Diagnose delays and failures','HTTP rate/error/duration, JVM metrics, business event logs, outbox attempt counter, service graph and trace/log navigation.'),
 ('Reproduce the demonstration','Pinned observability versions, checksum-verified agent, Compose overlay, scripts and expected outcomes below.'),
 ('Run tests on demand','Separate opt-in workflow: Run workflow or manually add the run-otel-e2e PR label; no push/build trigger.'),
 ('Keep handover current','This HTML is generated by '+file('scripts/render-poc-guide.py')+'; the manual workflow regenerates it and uploads it with results.')]))


section('value','Why OpenTelemetry helps this payment platform',p('The main demonstration is an investigation: take a payment ID, find its business log, follow the trace across services and asynchronous delivery, then use metrics to see whether the same problem affects other requests. The instrumentation turns separate service activity into evidence that developers and production support can navigate.')+
table(['Signal','What it tells you','What this PoC displays'],[
 ('Logs — events','What happened and which business operation it affected.','Payment outcome, risk decision, bank failure, outbox retry and notification events in Loki.'),
 ('Traces — one request','Where time was spent and which dependent operation failed. A span represents one operation; trace IDs connect related spans.','HTTP, JDBC, outbox.publish and RabbitMQ consumer spans in Tempo, with service, duration, status and parent relationships.'),
 ('Metrics — trends','How often something happens and whether latency, errors or resource usage are increasing.','HTTP rate/errors/p95, JVM memory, outbox publish attempts, service graph rates and telemetry target health in Prometheus/Grafana.')])+
p('OpenTelemetry generates, collects, processes and exports telemetry. In this PoC, Loki stores logs, Tempo stores traces, Prometheus stores metrics and Grafana displays them. Business log messages still come from application code; the Java agent captures them with service and active trace/span context. A healthy endpoint alone cannot establish that a payment or eventual notification succeeded.')+
table(['Investigation / advantage','Feature used','Practical result'],[
 ('Which service made this payment slow?','Request trace and operation durations','Inspect the bank HTTP client and JDBC spans before deciding which service to change.'),
 ('Why did payment return an unknown outcome?','Business outcome logs plus downstream error spans','Separate a bank decline from a timeout/500 that requires reconciliation; preserve the original idempotency ID.'),
 ('Payment succeeded; why is notification missing?','Persisted outbox context, producer/consumer spans, attempt metric and retry logs','Follow delivery after the HTTP response and identify a broker outage or consumer problem.'),
 ('Is one request slow, or are many requests affected?','Individual traces plus HTTP p95/rate/error metrics','Use the trace for a concrete example and aggregate metrics for the incident scope.'),
 ('HTTP is green but business outcomes are failing','Business event dashboard and risk/decline logs','Detect domain failures that HTTP 5xx graphs cannot describe.'),
 ('Are the dashboards empty because telemetry failed?','Prometheus targets, Collector health and Tempo ingestion rate','Investigate the observation pipeline before treating missing data as healthy behavior.'),
 ('What changed after a developer fix?','Comparable operation spans, logs and aggregate metrics','Check whether the measured bottleneck improved; this PoC has not measured an MTTR or capacity improvement.'),
 ('How can trace volume be reduced?','Optional tail sampling','Retain error/slow traces and probabilistically reduce normal traces. The recorded small sample verifies reduction, not an exact retention percentage.'),
 ('Can the backend change later?','Standard OTLP export and Collector routing','Application instrumentation is separated from backend routing; any backend replacement still requires its own integration validation.')])+
p('Read the screenshots as evidence: the operations dashboard shows a bank latency spike and HTTP 500 activity; the business dashboard shows completed, declined and reconciliation events; the telemetry dashboard shows outbox failure logs and its warning alert. The alert is visible in Prometheus/Grafana; pager delivery is not configured.')+
p('Concept references: ')+link('https://opentelemetry.io/docs/concepts/signals/','OpenTelemetry signals')+' · '+link('https://opentelemetry.io/docs/concepts/signals/logs/','Log correlation')+' · '+link('https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/configure-trace-to-logs/','Grafana trace/log navigation'))

log_examples=[]
log_files=sorted((ROOT/'artifacts').glob('logs-*.json'))
if log_files:
    capture=json.loads(log_files[0].read_text())
    for stream in capture.get('data',{}).get('result',[]):
        labels=stream.get('stream',{})
        for row in stream.get('values',[]):
            if any(event in row[1] for event in ('event=HTTP_REQUEST','event=OUTBOX_PUBLISHED')):
                log_examples.append({'timestamp_utc':datetime.datetime.fromtimestamp(int(row[0])/1e9,datetime.timezone.utc).isoformat(),'service_name':labels.get('service_name'),'severity_text':labels.get('severity_text'),'trace_id':labels.get('trace_id'),'span_id':labels.get('span_id'),'body':row[1]})
                break
        if len(log_examples)==2:break
example_trace=next((x['trace_id'] for x in log_examples if x.get('trace_id')), 'REPLACE_WITH_TRACE_ID')
log_body=p('A log row has a timestamp, severity, service, message and, when logged inside an active span, trace_id/span_id. service_name narrows the service; the business/payment ID identifies the operation; trace_id joins related service activity; span_id identifies the particular operation. Startup/background logs may have no active trace. Trace IDs are queried as structured metadata, rather than creating a Loki stream for every request.')
if log_examples:
    log_body+=p('Selected fields from actual captured Loki records, formatted for readability. These are observed application events, not invented demonstration logs. The evidence archive contains the complete response in '+log_files[0].name+'.')+code(json.dumps(log_examples,indent=2))
else:
    log_body+=p('No captured log response exists in this checkout. Run manual acceptance to populate actual record examples; the queries below describe how to investigate a fresh run.')
failure_examples=[]
failure_capture=read_artifact('recent-payment-logs.json', {})
seen=set()
for stream in failure_capture.get('data',{}).get('result',[]):
    labels=stream.get('stream',{})
    for row in stream.get('values',[]):
        for event in ('OUTBOX_PUBLISH_FAILED','PAYMENT_RECONCILIATION_REQUIRED'):
            if 'event='+event in row[1] and event not in seen:
                seen.add(event)
                failure_examples.append({'timestamp_utc':datetime.datetime.fromtimestamp(int(row[0])/1e9,datetime.timezone.utc).isoformat(),'service_name':labels.get('service_name'),'severity_text':labels.get('severity_text'),'trace_id':labels.get('trace_id'),'body':row[1]})
if failure_examples:
    log_body+='<h3>Actual failure log examples</h3>'+code(json.dumps(failure_examples,indent=2))+p('OUTBOX_PUBLISH_FAILED names the messaging failure and retry attempt. PAYMENT_RECONCILIATION_REQUIRED ties an uncertain bank outcome to a payment ID. These logs explain different operational problems; a generic error count cannot make that distinction.')
log_body+= '<h3>From payment ID to logs to trace</h3>'+bullets([
 'Start the local stack and create a small payment as demo / demo123. Copy its actual payment ID. Open Grafana on localhost:3001 and sign in as admin / otel-demo-admin.',
 'Choose Explore → Loki. Select a time window covering the request. Search the payment-service using the payment-ID query below. Expand a matching business log to read the event, outcome and trace_id.',
 'Use the configured Tempo link beside trace_id, or paste that trace ID into Explore → Tempo. Inspect the waterfall, each span’s service/status/duration and parent relationships. This validates an operation, rather than merely showing that containers are UP.',
 'Search all service logs using the same trace ID. Follow payment → gateway/bank/JDBC and the saved outbox.publish → RabbitMQ → notification path. Async delivery can finish after the HTTP response.',
 'Open the three dashboards to compare the particular request with request-rate, latency, business-outcome and outbox trends. A p95 panel is an aggregate over a time window, not the duration of the selected trace.'
])+code('{service_name="payment-service"} |= "REPLACE_WITH_PAYMENT_ID"\n\n{service_name=~".+"} | trace_id="'+example_trace+'"\n\n{service_name="payment-service"} |= "OUTBOX_PUBLISH_FAILED"\n\n{service_name="notification-service"} |~ "NOTIFICATION_(EVENT_RECEIVED|DUPLICATE_SKIPPED|RETRY_REUSED)"')
log_body+=p('The captured trace ID above belongs to the completed evidence run. That temporary stack was removed; its old records are in the evidence ZIP, not in a new local Tempo/Loki instance. For a new live demo, use the new payment and trace IDs. If a link has no result, check the time range, backend health and whether that trace was retained.')
log_body+='<h3>Where logs appear</h3>'+table(['View','What you see','When to use it'],[
 ('Grafana Explore → Loki','Searchable application events and service/trace metadata','Find a business operation and correlate its related logs.'),
 ('Operations dashboard → Correlated service logs','Logs for the selected service(s), alongside rate/p95/JVM metrics','Move from a symptom graph to relevant event details.'),
 ('Business dashboard','Outcome counts, notification activity and reconciliation/risk events','Investigate business failures even when HTTP responses are successful.'),
 ('Telemetry dashboard','Outbox failure events, retry attempts, alert state and scrape targets','Investigate delivery failures and telemetry availability.'),
 ('docker compose logs','Container console output, including startup and exporter errors','Diagnose failures when central telemetry is unavailable.'),
 ('Evidence ZIP','Raw Loki/Tempo/Prometheus responses and Compose logs from the passing run','Review the demonstration later, after the temporary services have stopped.')])
log_body+=code('bash scripts/otel-compose.sh logs -f payment-service gateway-service notification-service')
section('log-walkthrough','How logs appear and connect to a trace',log_body)

section('worked-cases','Worked investigations: what to show and why it matters',table(['Case to demonstrate','What appears in the UI / telemetry','What the evidence helps you decide'],[
 ('Successful payment and eventual notification','COMPLETED; PAYMENT_COMPLETED and OUTBOX_PUBLISHED events; connected HTTP/JDBC/outbox/Rabbit consumer spans; notification SENT.','Confirm both synchronous money movement and asynchronous delivery. The recorded recovery trace has 84 spans across six services; authentication is a separate request.'),
 ('Insufficient funds / risk limit','Business decline or risk rejection in the application; corresponding business-event/risk panels and logs.','An HTTP-success response may contain a business FAILED result. Investigate the domain decision instead of escalating a server outage.'),
 ('Slow bank','RECONCILIATION_REQUIRED; gateway HTTP client error/timeout spans; elevated downstream latency; reconciliation logs.','The captured slow-failure trace contains an approximately five-second gateway client error span. Different deadlines can let downstream work outlive its caller. Preserve the original operation ID and investigate the ledger.'),
 ('Bank HTTP 500','Bank 500/error span; gateway fallback/unknown outcome; reconciliation events and HTTP-error activity.','Locate the failing dependency and distinguish uncertain money movement from a confirmed decline.'),
 ('Broker outage','Payment still commits; OUTBOX_PUBLISH_FAILED events and failure counter increase; warning alert; notification catches up after restart.','Identify delivery delay separately from payment failure. The live suite verified catch-up; do not create a duplicate payment.'),
 ('Collector outage','Payment remains available; agent/exporter errors can appear in container logs; a complete fresh trace is observed after restart/readiness recovery.','Separate a telemetry outage from an application outage. In-flight telemetry can be lost; missing logs are not evidence that a request never happened.'),
 ('Notification duplicate / poison payload','Real RabbitMQ integration tests verify one delivery for duplicate events and bounded retries ending in DLQ.','Investigate consumer deduplication/redrive safely. This is Testcontainers evidence; the three dashboard screenshots do not independently prove DLQ behavior.'),
 ('Tail sampling','A real bank error trace and seven-second slow trace are retained; normal traffic is reduced; full-trace Collector restored.','Understand retention/cost trade-offs. Sampled trace-derived rates are not total request counts; use application metrics for request-volume/SLO calculations.')])+
p('For the manager: demonstrate one successful payment, one slow/error payment and one broker outage. For each, show the user-facing outcome, the matching log, the trace/dependency responsible, the affected metric panel and the operational next step. The value is this connected investigation; a screenshot of a running server alone does not establish it.'))

services=[('Frontend',3000,'frontend','React customer screens, support/admin health and observability links','Browser → API Gateway'),('API Gateway',8088,'api-gateway','Routing, JWT/roles, correlation headers, operations health','Auth / Customer / Payment / Notification'),('Auth',8079,'auth-service','BCrypt-backed demo login, JWT issuance','PostgreSQL auth schema'),('Customer',8084,'customer-service','Customer profile and linked account','PostgreSQL customer schema'),('Payment',8080,'payment-service','Payment/P2P/refund, ownership, risk, reconciliation, outbox','Customer / Gateway / PostgreSQL / RabbitMQ'),('Gateway adapter',8081,'gateway-service','Bank HTTP client, timeout and circuit breaker','Mock Bank'),('Mock Bank',8082,'mock-bank-service','Simulated balances, debit/transfer/refund ledger and failure lab','PostgreSQL bank schema'),('Notification',8083,'notification-service','Consumer dedupe, retry/DLQ, simulated delivery','RabbitMQ / PostgreSQL notification schema')]
section('services','Services and end-to-end flow',table(['Service','Local port','Responsibility','Dependencies','Source'],[(name,str(port),purpose,deps,file(path)) for name,port,path,purpose,deps in services])+
p('Happy path: browser → API Gateway → Payment → Customer ownership check → Gateway adapter → Mock Bank → bank ledger. Payment state and outbox event are committed together. A scheduled relay restores saved W3C context, opens outbox.publish, sends via RabbitMQ and waits for publisher confirm. Notification consumes and persists a deduplicated simulated delivery.')+
p('The relay keeps traceparent and tracestate in nullable V6 migration columns. Existing events without context create new roots. Baggage is deliberately not persisted. Agent instrumentation handles HTTP, JDBC and messaging; only the durable scheduling boundary needs explicit context restoration. Retries after long outages can appear later than the original request, so widen the trace/log time window.')+
p('Telemetry path: every Java process exports OTLP/HTTP → Collector. Traces go to Tempo; logs to Loki native OTLP; application metrics are exposed by the Collector for Prometheus scraping. Tempo produces span metrics and service graphs into Prometheus via remote write. Grafana reads all three backends.'))

section('start','Recreate locally',p('Convenience commands: bash scripts/run-poc.sh start builds and starts the demo; test runs live business/telemetry/resilience checks; report refreshes evidence; stop shuts down; reset deletes this disposable project’s state. Browser screenshots are captured by the GitHub manual workflow.')+p('Prerequisites: Git, Java 21, Maven, Docker with Compose v2, Python 3, curl, jq and sha256sum. Allow roughly 12 GB RAM for a comfortable local demo. Containers and dependencies need internet access on first build. Use a fresh disposable stack for deterministic tests; fixed smoke-test IDs and bank balances make reusing old state unsuitable.')+
code('''git clone https://github.com/srinu7893/otel-payment-platform-poc.git
cd otel-payment-platform-poc
# Before merge, select the implementation branch:
git checkout feature/otel-observability-manual-e2e
export COMPOSE_PROJECT_NAME=otel-demo
mvn -B clean verify
bash scripts/setup-otel-agent.sh
bash scripts/otel-compose.sh config --quiet
bash scripts/otel-compose.sh run --rm --no-deps otel-collector validate --config=/etc/otelcol/config.yaml
bash scripts/otel-compose.sh run --rm --no-deps --entrypoint promtool prometheus check config /etc/prometheus/prometheus.yml
bash scripts/otel-compose.sh up --build -d
bash scripts/e2e/wait-ready.sh''')+
p('Backend Dockerfiles copy packaged target/*.jar; building with Maven first is required. The frontend container builds its own bundle. Starting without docker-compose.otel.yml keeps the original baseline agent-free.')+
table(['Destination','Link / demo login'],[
 ('Customer / Support UI',link('http://localhost:3000','http://localhost:3000')+' · demo / demo123 or support / support123'),
 ('Grafana dashboards',link('http://localhost:3001/d/payment-poc','Payment operations')+' · admin / otel-demo-admin (override GRAFANA_ADMIN_PASSWORD before startup)'),
 ('Grafana pipeline dashboard',link('http://localhost:3001/d/telemetry-pipeline','Telemetry pipeline health')),
 ('Grafana business dashboard',link('http://localhost:3001/d/payment-business','Business events and reconciliation')),
 ('Prometheus',link('http://localhost:9090','Queries, targets and alert rules')),
 ('Tempo readiness',link('http://localhost:3200/ready','Trace backend health')),
 ('Loki readiness',link('http://localhost:3100/ready','Log backend health')),
 ('Collector readiness',link('http://localhost:13133','Collector health')),
 ('RabbitMQ',link('http://localhost:15672','Queues / DLQ')+' · payments / payments'),
 ('API contract',link('http://localhost:8088/swagger-ui.html','Swagger UI')+' · '+file('docs/openapi-baseline.yaml'))])+
p('New telemetry ports bind to loopback. Existing application/database/broker ports still use the baseline bindings: this is a trusted local demo, not an internet-facing deployment. Remote use requires ingress/auth/TLS and frontend VITE_GRAFANA_URL configuration.')+
code('''# Stop without deleting telemetry volumes:
bash scripts/otel-compose.sh down
# Reset only this disposable demo (deletes its telemetry volumes and demo state):
bash scripts/otel-compose.sh down -v --remove-orphans'''))

section('tests','Manual automated acceptance',p('GitHub → Actions → manual-otel-e2e → Run workflow. Select the intended ref and choose whether to include broker/Collector outages. Before merge, manually add the run-otel-e2e label to the same-repository PR. Remove/re-add the label for a new run. The Run workflow button becomes available once workflow_dispatch exists on the default branch. Ordinary CI retains backend tests and build validation, but does not start the stack or run E2E.')+
p('For local testing, keep the same COMPOSE_PROJECT_NAME used at startup. The resilience option stops only that Compose project’s demo broker/Collector. Run scripts in this order on fresh state:')+
code('''bash scripts/e2e/business-smoke.sh
RESILIENCE=true python3 scripts/e2e/otel_acceptance.py
bash scripts/pre_otel_acceptance.sh
python3 scripts/e2e/live-traffic.py
python3 scripts/e2e/advanced-sampling.py
python3 scripts/e2e/capture-evidence.py
python3 scripts/render-poc-guide.py''')+
p('The manual workflow runs Maven unit and Testcontainers integration tests, validates backend configs, builds/starts the stack, checks business success/failure paths, queries real telemetry backends, collects diagnostic logs and always removes its disposable stack. Evidence artifact: otel-poc-evidence-<run number>. Includes Surefire reports, actual OTel assertion results, trace ID summary, Compose logs and this HTML. A failed test fails the workflow; missing telemetry is not treated as a skipped success.')+
table(['Scenario','Expected result','Executable source'],[
 ('Login, payment, P2P and refund','COMPLETED; expected notification becomes SENT; refund ties to original payment',file('scripts/e2e/business-smoke.sh')),
 ('Payment/refund replay','Same original IDs; bank integration verifies one balance change',file('scripts/e2e/business-smoke.sh')+' / '+file('mock-bank-service/src/test/java/com/srinu/payments/bank/integration/BankPostgresIntegrationTest.java')),
 ('Insufficient funds','Business FAILED response; distinguish from HTTP/server failure',file('scripts/e2e/business-smoke.sh')),
 ('Risk rejection','HTTP 422 + RISK_LIMIT_EXCEEDED / MAX_TRANSACTION_AMOUNT',file('scripts/e2e/business-smoke.sh')),
 ('Authentication and role failures','401 for no token / invalid login; 403 for customer operations route / wrong source account',file('scripts/e2e/otel_acceptance.py')),
 ('Slow bank / simulated bank 500','RECONCILIATION_REQUIRED plus an actual downstream error trace; never blindly retry money movement',file('scripts/e2e/otel_acceptance.py')+' / '+file('scripts/pre_otel_acceptance.sh')),
 ('HTTP + JDBC + outbox + Rabbit consumer trace','One trace has six required service names, DB spans, outbox.publish and valid parent references',file('scripts/e2e/otel_acceptance.py')),
 ('Metrics/log integration','Seven service HTTP metric series, JVM and custom outbox metric, service graph; exact payment trace ID in Loki',file('scripts/e2e/otel_acceptance.py')),
 ('Advanced tail sampling','Real bank 500 and seven-second traces retained; normal traffic reduced; restores full-trace Collector afterward',file('scripts/e2e/advanced-sampling.py')),
 ('Broker outage and recovery','Payment commits; outbox failure metric appears; notification catches up after broker restarts',file('scripts/e2e/otel_acceptance.py')),
 ('Collector outage and recovery','Payment remains available; a fresh trace reaches Tempo after restart. No promise of lossless outage telemetry.',file('scripts/e2e/otel_acceptance.py')),
 ('Poison event and redelivery','Bounded retries → DLQ with x-death; duplicate event results in one delivery',file('notification-service/src/test/java/com/srinu/payments/notification/integration/NotificationRabbitIntegrationTest.java')),
 ('Saved context / legacy event','W3C trace ID, span ID and tracestate survive scheduler boundary; invalid context cannot inherit scheduler trace',file('payment-service/src/test/java/com/srinu/payments/payment/outbox/OutboxTraceContextTest.java'))]))

section('demo','Manual manager demonstration',bullets([
 'Open the customer UI and sign in as demo / demo123. Create a small merchant payment using ACC1001. Note its payment ID and confirm COMPLETED.',
 'Sign in as support / support123 in another browser session. Open the operations dashboard and verify service health. Use the Observability card to open Grafana.',
 'In Grafana Explore choose Loki and search '+code('{service_name="payment-service"} |= "PAYMENT_ID"')+'Replace PAYMENT_ID with the actual ID. Expand the log metadata; open trace_id in Tempo. Follow edge → payment → customer/gateway → bank → JDBC, then outbox.publish → RabbitMQ → notification.',
 'Explain request duration versus eventual notification delay. The async consumer can finish after the HTTP response. Examine parent spans, database duration and service map rather than summing overlapping durations.',
 'Refund the completed payment. Check refund history and PAYMENT_REFUNDED notification. Replay via the smoke script and explain bank-side idempotency and consumer deduplication.',
 'Use amount 6000 on a fresh ACC1001 balance to demonstrate insufficient funds. Use 100001 for configured transaction-risk rejection. Explain why a business failure can return HTTP 2xx and why HTTP error graphs alone are insufficient.',
 'Use slowdemo / slowdemo123 with ACC-SLOW and errordemo / errordemo123 with ACC-ERROR for timeout/500 scenarios. Confirm reconciliation state, inspect downstream error/latency spans and distinguish unknown outcome from decline.',
 'Run the optional resilience suite. Show outbox failure counters and recovery after broker restart. Show application availability during Collector outage, then fresh traces after recovery.',
 'Finish with the workflow evidence artifact and Evidence section below. Demonstrate passed assertions from an actual run; label any unexecuted scenario explicitly.'
]))

section('support','Support and developer runbooks',table(['Symptom','Investigation','Safe action'],[
 ('Payment seems stuck','Look up business ID in support UI; search corresponding log → trace. Inspect gateway timeout, bank ledger and reconciliation logs.','Keep original payment/idempotency ID. Do not create a replacement payment while the outcome is unknown.'),
 ('HTTP looks healthy but payments fail','Use PAYMENT_NOT_COMPLETED and PAYMENT_RECONCILIATION_REQUIRED log events; inspect risk/bank decisions.','Separate business rejection from transport failure; use the documented reconciliation path.'),
 ('Notification missing','Check outbox status/retry logs; inspect payments.notification and DLQ; follow producer/consumer spans.','Restore broker first. Investigate poison payload before deliberate redrive; preserve event ID for dedupe.'),
 ('Dashboard empty','Prometheus Targets → otel-applications; check Collector logs, OTLP endpoint, agent mount and service.name. Query metrics directly.','Verify actual series names and selected time window; do not equate empty data with zero errors.'),
 ('Logs absent but traces exist','Check Collector logs pipeline, Loki /ready, native OTLP configuration and structured metadata.','Check Logback instrumentation and widen log time range. Do not enable credential/header dumping.'),
 ('Trace fragments','Inspect saved outbox traceparent and publisher/consumer spans. Check late retries and sampling settings.','Use unsampled acceptance mode; delayed outbox traces may arrive after sampling decisions.'),
 ('Slow request','Compare HTTP p95 to individual spans, JDBC time, JVM memory and downstream bank latency.','Optimize the measured bottleneck; keep bounded timeouts and money-movement idempotency.')])+
p('Developers add business spans around meaningful work using the OpenTelemetry API supplied by the agent; do not install a second SDK or tracing starter alongside it. Use bounded dimensions such as outcome and operation. Never use payment IDs, account numbers, email, JWT or raw URL values as metric labels. The custom outbox metric counts publish attempts confirmed by the broker, not unique committed payments; database rollback and retry can increase it.')+
code('''# Loki: operational failures
{service_name="payment-service"} |~ "PAYMENT_(NOT_COMPLETED|RECONCILIATION_REQUIRED)"
# Loki: exact known trace
{service_name=~".+"} | trace_id="REPLACE_WITH_TRACE_ID"
# Tempo TraceQL: bank errors
{ resource.service.name = "mock-bank-service" && status = error }
# Prometheus: HTTP p95 (seconds)
histogram_quantile(0.95, sum by (le,service_name) (rate(http_server_request_duration_seconds_bucket[5m])))
# Prometheus: outbox publish failures
sum(increase(poc_outbox_publish_attempts_total{outcome="failure"}[5m]))'''))

section('coverage','OpenTelemetry coverage: basic to advanced',table(['Capability','This increment','Boundary / remaining work'],[
 ('Instrumentation','Java agent attached to all seven backend JVMs; HTTP/JDBC/RabbitMQ/JVM; Micrometer bridge enabled','Browser RUM, continuous profiling, host/Kubernetes metrics and broker-depth metrics are not implemented.'),
 ('Signals and context','Traces, metrics, logs, W3C propagation, durable outbox context, trace/log links','Global baggage propagation is available; arbitrary baggage is not stored in outbox.'),
 ('Business observability','Custom outbox.publish span and attempt metric; business outcome log panels','No full custom payment SLO/error-budget instrumentation or complete domain audit store.'),
 ('Collector','OTLP gRPC/HTTP receivers; resource, memory limit, privacy attribute deletion, batching, bounded exporter queues/retry','Queues are memory-backed. No guarantee of lossless delivery through lengthy outages or restarts.'),
 ('Visualization','Provisioned operations, business and pipeline dashboards; trace search, service graph, exemplars configured','The Evidence section records rendered dashboards and backend queries. Exemplars depend on sampled data and compatible panels.'),
 ('Sampling','Default always_on for deterministic demo; isolated tail experiment retains errors/slow traces + 10% baseline','The manual workflow runs a separate real-request sampling experiment after deterministic full-trace E2E. Error/slow rules require all spans for a trace to reach one sampling Collector.'),
 ('Alerts','Prometheus rules for telemetry scrape failure, outbox failure and span error ratio','No Alertmanager routing, pager/email delivery or production SLO policy.'),
 ('Resilience','Business idempotency/reconciliation plus broker/Collector outage tests','Not a load, capacity, HA, disaster recovery or production-readiness certification.'),
 ('Security/privacy','No authorization/cookie capture; selected sensitive DB attributes removed; bounded metric labels','Existing logs contain synthetic customer/business data. Attribute deletion does not sanitize arbitrary log bodies. Review/redact before using real data.'),
 ('Deployment','Local single-node Compose with retained telemetry volumes and 24h backend retention','GCP runtime, workload identity, secrets, TLS, ingress, scaling, durable telemetry queues and backups remain decisions.')])+
p('Optional sampling experiment (do not run deterministic trace assertions with it enabled):')+
code('''docker compose -f docker-compose.yml -f docker-compose.otel.yml -f docker-compose.sampling.yml \
  run --rm --no-deps otel-collector validate --config=/etc/otelcol/config.yaml --config=/etc/otelcol/tail.yaml
docker compose -f docker-compose.yml -f docker-compose.otel.yml -f docker-compose.sampling.yml up -d otel-collector
# After experimentation, restore full-trace acceptance configuration:
bash scripts/otel-compose.sh up -d --force-recreate otel-collector''')+
p('Tail sampling waits 30 seconds and retains errors, latency over 2 seconds, and a 10% baseline. Late outbox retries can exceed this decision window; evaluate span links or a larger window before production. Service-graph/span-rate metrics derived after sampling describe sampled traffic, not total traffic; use unsampled application metrics for accurate request SLOs.'))

section('findings','Review findings and remaining decisions',bullets([
 '<strong>Fixed:</strong> transaction outbox lacked durable trace context. V6 adds nullable traceparent/tracestate and the relay restores request context around publish.',
 '<strong>Fixed:</strong> full-stack smoke and pre-OTel acceptance ran on ordinary CI. They now live in a manual-only workflow, along with telemetry and resilience assertions.',
 '<strong>Fixed after live testing:</strong> async React form reset, browser locale, Loki all-service selection, Collector recovery readiness and the OpenAPI curl pipe race; repeated manual runs capture these behaviors.',
 '<strong>Fixed:</strong> no telemetry backends or operational trace/log entry point. The overlay provisions all three signal paths and support UI links.',
 '<strong>Known baseline boundary:</strong> internal customer/bank endpoints rely on trusted-network deployment; demo JWT secrets/accounts and exposed service ports must not be deployed publicly. See '+file('docs/SECURITY_BASELINE.md')+' and '+file('docs/SERVICE_IDENTITY_STRATEGY.md')+'.',
 ('<strong>Verified live:</strong> agent/library compatibility, backend configurations, connected payment traces, metrics/logs, recovery scenarios, browser screens, three rendered dashboards and tail sampling passed in the recorded manual run.' if verified else '<strong>Verification gate:</strong> check recorded workflow outcomes and assertion results below. Only a fully passing run verifies the live integration.'),
 '<strong>Production scope:</strong> choose GCP runtime, backend/vendor, IAM/secrets, retention/cost, broker management and support escalation policy. All OpenTelemetry ecosystem features cannot meaningfully be declared complete by one local PoC.'
]))

evidence=p('Live integration status: '+('VERIFIED — every recorded workflow stage and acceptance assertion passed.' if verified else 'See individual recorded outcomes; full live verification is not established by source configuration alone.'))
evidence+=p('Tested application source revision: '+revision+'; source ref: '+ref+'. Generated '+datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')+'.')
evidence+=p('Reproduce this exact source snapshot with git checkout '+revision+' before building. Source links follow the implementation branch; the revision above identifies the tested snapshot.')
if os.environ.get('GITHUB_RUN_ID'):
    evidence+=p('GitHub run: ')+link('https://github.com/'+os.environ['GITHUB_REPOSITORY']+'/actions/runs/'+os.environ['GITHUB_RUN_ID'],'Open exact workflow run')
if test_totals['tests']:
    evidence+=table(['Backend tests','Failures','Errors','Skipped'],[tuple(str(test_totals[k]) for k in ('tests','failures','errors','skipped'))])
if pipeline:
    evidence+=table(['Workflow stage','Actual outcome'],[(e(k),e(v)) for k,v in pipeline.items()])
if results:
    evidence+=table(['Telemetry/security/resilience assertion','Actual result','Detail'],[(e(x['scenario']),e(x['status']),e(x.get('error',str(x.get('seconds',''))+' seconds'))) for x in results])
else:
    evidence+='<div class="notice">NOT RUN HERE: no live OTel acceptance result file is present. Docker was unavailable in the authoring workspace; backend tests and live telemetry must be verified in the manual workflow. Do not interpret this guide as a successful runtime test report.</div>'
trace=read_artifact('trace-evidence.json', {})
if trace:
    evidence+='<h3>Connected payment trace</h3>'+code(json.dumps(trace,indent=2))
targets=read_artifact('prometheus-targets.json', {}).get('data',{}).get('activeTargets',[])
if targets:
    evidence+=table(['Prometheus target','Observed health'],[(e(x['labels'].get('job','')),e(x['health'])) for x in targets])
metric_names=read_artifact('prometheus-series.json', {}).get('data',[])
if metric_names:
    evidence+=p(str(len(metric_names))+' metric names exposed across the application and telemetry backends; the acceptance suite separately asserts required application, JVM, outbox and service-graph series.')
alerts=read_artifact('prometheus-alerts.json', {}).get('data',{}).get('alerts',[])
if alerts:
    evidence+=table(['Recorded alert','Observed state'],[(e(x['labels'].get('alertname','')),e(x['state'])) for x in alerts])
for title, data in [('Browser acceptance',browser),('Measured demonstration traffic',traffic),('Advanced tail-sampling experiment',sampling)]:
    if data:
        evidence+='<h3>'+e(title)+'</h3>'+code(json.dumps(data,indent=2))
screen_captions={
 '01-customer-overview':'Customer overview: the entry point for producing a real payment and its telemetry.',
 '02-browser-payment-completed':'Payment completed: the customer outcome to correlate with PAYMENT_COMPLETED, bank spans and eventual notification.',
 '03-browser-transfer-completed':'Transfer completed: the P2P customer flow exercised by the browser.',
 '04-support-operations':'Support view: live service health, problem payments and notification activity; use IDs to investigate the corresponding telemetry.',
 '05-payment-poc':'Operations dashboard: locate the bank latency/error spike, compare request/JVM trends and read correlated service logs.',
 '06-payment-business':'Business dashboard: distinguish completed payments, declines and unknown outcomes; inspect notification and reconciliation/risk events.',
 '07-telemetry-pipeline':'Telemetry health: three scrape targets UP, Tempo ingesting spans, outbox retry attempts and an outage warning alongside its failure logs.'
}
screens=sorted((ROOT/'artifacts/screenshots').glob('*.png')) if os.environ.get('POC_EMBED_SCREENSHOTS','true').lower()=='true' else []
if screens:
    evidence+='<h3>Captured from the live run</h3>'+''.join('<figure><figcaption>'+e(screen_captions.get(f.stem,f.stem))+'</figcaption><img style="max-width:100%;border:1px solid #ccd" alt="'+e(f.stem)+'" src="data:image/png;base64,'+base64.b64encode(f.read_bytes()).decode()+'"></figure>' for f in screens)
section('evidence','Execution evidence',evidence+p('Backend Surefire reports, raw trace/log/metric responses, database summaries, Compose logs and screenshots are included in the downloadable evidence archive. Frontend/container build results are recorded in ordinary CI and linked from the pull request. A workflow artifact is a snapshot of that run, not a permanent promise of current health. The manual guide and scenario table describe expected outcomes; this section records observed results only.'))

sources=[('OTel Java agent','https://opentelemetry.io/docs/zero-code/java/agent/'),('Agent configuration','https://opentelemetry.io/docs/zero-code/java/agent/configuration/'),('Custom API with agent','https://opentelemetry.io/docs/zero-code/java/agent/api/'),('Collector configuration','https://opentelemetry.io/docs/collector/configuration/'),('Loki native OTLP ingestion','https://grafana.com/docs/loki/latest/send-data/otel/'),('Tempo service graphs','https://grafana.com/docs/tempo/latest/metrics-from-traces/service_graphs/'),('Tail sampling processor','https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor'),('Manual GitHub workflows','https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow')]
section('sources','Source links and maintenance',table(['Item','Repository source'],[(e(label),file(path)) for label,path in [('Base stack','docker-compose.yml'),('OTel overlay','docker-compose.otel.yml'),('Collector','observability/collector.yaml'),('Tempo','observability/tempo.yaml'),('Loki','observability/loki.yaml'),('Prometheus / alerts','observability/prometheus.yaml'),('Dashboard JSON','observability/grafana/dashboards'),('Datasource links','observability/grafana/provisioning/datasources/datasources.yaml'),('Manual workflow','.github/workflows/manual-otel-e2e.yml'),('Acceptance scripts','scripts/e2e'),('HTML generator','scripts/render-poc-guide.py')]])+
bullets([link(url,title) for title,url in sources])+
p('When changing service topology, telemetry config or scenario behavior, update the generator’s capability/scenario tables in the same change. Run python3 scripts/render-poc-guide.py and commit the regenerated docs/POC_GUIDE.html. After each manual run, download the refreshed HTML and evidence artifact. Results are never silently promoted to passed.'))
nav=''.join('<a href="#'+key+'">'+e(title)+'</a>' for key,title,_ in sections)
body=''.join('<section id="'+key+'"><h2>'+e(title)+'</h2>'+content+'</section>' for key,title,content in sections)
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Payment Platform · OpenTelemetry POC guide</title><style>
:root{color-scheme:light;--ink:#142e3e;--accent:#007c83}*{box-sizing:border-box}body{margin:0;background:#f2f6f8;color:var(--ink);font:16px/1.6 system-ui,sans-serif}header{background:#123546;color:white;padding:48px max(5vw,24px)}header h1{max-width:1000px;margin:8px 0;font-size:clamp(30px,4vw,48px);line-height:1.15}header p{color:#cae4e9}main{max-width:1280px;margin:auto;padding:24px}nav{display:flex;flex-wrap:wrap;gap:8px;padding-bottom:16px}nav a{background:white;padding:7px 12px;border-radius:6px;font-size:13px}section{background:white;border:1px solid #dde7ec;border-radius:10px;padding:28px;margin:20px 0;scroll-margin-top:16px}h2{font-size:26px;margin:0 0 18px;color:#12475c}a{color:#006e82;overflow-wrap:anywhere}pre{background:#102c3c;color:#e1f5ee;padding:18px;border-radius:7px;overflow:auto;font:13px/1.6 ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th{text-align:left;background:#eaf3f5}th,td{padding:12px;border-bottom:1px solid #dce7ec;vertical-align:top}li{margin:12px 0}.notice{background:#fff3d5;border-left:5px solid #d18a00;padding:18px;font-weight:600}.tag{letter-spacing:.14em;text-transform:uppercase;font-size:12px;color:#9ce0dd}@media print{body{background:white;font-size:11px}header{padding:20px}nav{display:none}main{padding:0}section{break-inside:auto;border:0;padding:12px}h2{break-after:avoid}tr{break-inside:avoid}pre{color:#102c3c;background:#f2f6f8}}@media(max-width:600px){main{padding:10px}section{padding:16px}th,td{padding:8px;min-width:130px}}
</style></head><body><header><div class="tag">Engineering / Support / Manager handover</div><h1>Payment Platform<br>OpenTelemetry POC</h1><p>Understand the value. Follow a payment from logs to traces. Verify the evidence.</p></header><main><nav>'''+nav+'</nav>'+body+'</main></body></html>'
(ROOT/'docs/POC_GUIDE.html').write_text(html)
print('Generated docs/POC_GUIDE.html')
